import { Product } from '@/types';

export const products: Product[] = [
  // === ELECTRONICS (1 to 12) ===
  {
    id: 1,
    title: 'Zenith Quantum Pro Laptop',
    description: 'Ultra-thin powerhouse with OLED display and AI-enhanced performance.',
    longDescription: 'The Zenith Quantum Pro redefines portable computing. Featuring a stunning 14" OLED display with 2880x1800 resolution, this laptop delivers breathtaking visuals. Powered by the latest AI-enhanced processor with 32GB LPDDR5 RAM and a 1TB NVMe SSD, it handles everything from creative work to machine learning tasks effortlessly.',
    price: 1299.99,
    originalPrice: 1599.99,
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80',
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=80',
    ],
    category: 'Electronics',
    subcategory: 'Laptops',
    rating: 4.8,
    reviewCount: 342,
    inventory: 50,
    badge: 'sale',
    tags: ['laptop', 'oled', 'premium', 'ai'],
    specs: { 'CPU': 'AI-Enhanced 14-core', 'RAM': '32GB LPDDR5', 'Storage': '1TB NVMe SSD', 'Display': '14" OLED' },
  },
  {
    id: 2,
    title: 'Aero Pro Headphones X1',
    description: 'Studio-grade noise cancellation with 40-hour battery life.',
    longDescription: 'Experience music the way artists intended. The Aero Pro X1 features proprietary 40mm dynamic drivers tuned by sound engineers. Active Noise Cancellation 3.0 eliminates up to 98% of ambient noise, while Transparency Mode lets you stay aware of your surroundings.',
    price: 349.99,
    originalPrice: 429.99,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600&q=80',
    ],
    category: 'Electronics',
    subcategory: 'Audio',
    rating: 4.9,
    reviewCount: 891,
    inventory: 120,
    badge: 'bestseller',
    tags: ['headphones', 'anc', 'wireless', 'premium'],
    specs: { 'Driver': '40mm Dynamic', 'ANC': 'Active Noise Cancellation 3.0', 'Battery': '40 hours', 'Connectivity': 'Bluetooth 5.3' },
  },
  {
    id: 3,
    title: 'Lunar Series Smartwatch Ultra',
    description: 'Health monitoring reimagined with ECG, blood glucose & SpO2.',
    longDescription: 'The Lunar Ultra is more than a smartwatch — it\'s your personal health guardian. Featuring medical-grade ECG, continuous blood oxygen monitoring, and breakthrough non-invasive blood glucose tracking. Always-on AMOLED display is visible in bright sunlight.',
    price: 499.99,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80',
      'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&q=80',
    ],
    category: 'Electronics',
    subcategory: 'Wearables',
    rating: 4.7,
    reviewCount: 567,
    inventory: 80,
    badge: 'new',
    tags: ['smartwatch', 'health', 'titanium', 'ecg'],
    specs: { 'Case': 'Titanium Grade 5', 'Display': 'AMOLED 1.9"', 'Health': 'ECG, SpO2', 'Battery': '72 hours' },
  },
  {
    id: 4,
    title: 'CrystalView 4K Monitor Pro',
    description: '32" IPS 4K 165Hz display engineered for creative professionals.',
    longDescription: 'The CrystalView Pro delivers 3840x2160 resolution at a buttery smooth 165Hz refresh rate, making it perfect for both creative work and high-performance gaming. The factory-calibrated panel covers 99% DCI-P3 color space.',
    price: 899.99,
    originalPrice: 1099.99,
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&q=80',
    ],
    category: 'Electronics',
    subcategory: 'Monitors',
    rating: 4.6,
    reviewCount: 234,
    inventory: 35,
    badge: 'sale',
    tags: ['monitor', '4k', 'ips', 'hdr'],
    specs: { 'Resolution': '3840x2160', 'Refresh Rate': '165Hz', 'Panel': 'IPS', 'HDR': 'HDR1000' },
  },
  {
    id: 5,
    title: 'NovaCam 8K Action Camera',
    description: 'Capture 8K cinematic footage with AI stabilization in any condition.',
    longDescription: 'The NovaCam pushes action photography to its limits. Shoot in stunning 8K at 30fps or 4K at 120fps for ultra-smooth slow motion. AI-powered stabilization ensures perfectly smooth footage even during extreme activities.',
    price: 449.99,
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&q=80',
    ],
    category: 'Electronics',
    subcategory: 'Cameras',
    rating: 4.5,
    reviewCount: 189,
    inventory: 60,
    badge: 'new',
    tags: ['camera', '8k', 'action', 'waterproof'],
    specs: { 'Video': '8K@30fps', 'Stabilization': 'AI Hyper', 'Waterproof': '30m', 'Screen': '2.5" Touch' },
  },
  {
    id: 6,
    title: 'SoundBar Pro X9',
    description: 'Dolby Atmos 3D surround sound in a sleek, wall-mounted design.',
    longDescription: 'Transform your living room into a private cinema. Featuring 11.1.4 channel Dolby Atmos with up-firing drivers and wireless subwoofer for true immersive sound quality.',
    price: 699.99,
    originalPrice: 849.99,
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&q=80',
    ],
    category: 'Electronics',
    subcategory: 'Audio',
    rating: 4.7,
    reviewCount: 312,
    inventory: 45,
    badge: 'hot',
    tags: ['soundbar', 'dolby-atmos', 'home-theater'],
    specs: { 'Channels': '11.1.4 Dolby', 'Power': '1200W', 'Connectivity': 'eARC, Wi-Fi', 'Subwoofer': 'Wireless 10"' },
  },
  {
    id: 41,
    title: 'Apex Mechanical Keyboard',
    description: 'Hot-swappable mechanical keyboard with custom linear switches and RGB.',
    longDescription: 'The Apex features pre-lubed custom switches, dampening foam layers, and a heavy aluminum frame for premium typing acoustics. Dual-mode wireless connection gives latency-free performance.',
    price: 189.99,
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&q=80',
    ],
    category: 'Electronics',
    subcategory: 'Accessories',
    rating: 4.8,
    reviewCount: 154,
    inventory: 40,
    badge: 'hot',
    tags: ['keyboard', 'mechanical', 'rgb', 'wireless'],
    specs: { 'Layout': '75%', 'Switches': 'Linear Custom', 'Keycaps': 'PBT Double-shot', 'Battery': '4000mAh' },
  },
  {
    id: 42,
    title: 'Apex Wireless Gaming Mouse',
    description: 'Ultra-lightweight 54g gaming mouse with 30K optical sensor.',
    longDescription: 'Engineered for competitive gaming, the Apex mouse features zero-latency wireless tech, optical mouse switches rated for 90 million clicks, and a smooth PTFE glide base.',
    price: 129.99,
    originalPrice: 149.99,
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&q=80',
    ],
    category: 'Electronics',
    subcategory: 'Accessories',
    rating: 4.9,
    reviewCount: 221,
    inventory: 90,
    badge: 'sale',
    tags: ['mouse', 'gaming', 'wireless', 'ultra-light'],
    specs: { 'Weight': '54g', 'Sensor': '30K Optical', 'Battery': '90 hours', 'Polling Rate': '4000Hz' },
  },
  {
    id: 43,
    title: 'VR Vision Horizon Headset',
    description: 'Standalone virtual reality headset with dual micro-OLED 4K displays.',
    longDescription: 'Step into high-fidelity spatial computing. Featuring standalone tracking, a powerful GPU, pass-through cameras, and ergonomic strap system for extended usage comfort.',
    price: 999.99,
    image: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=600&q=80',
    ],
    category: 'Electronics',
    subcategory: 'VR',
    rating: 4.7,
    reviewCount: 88,
    inventory: 20,
    badge: 'new',
    tags: ['vr', 'headset', 'ar', 'gaming'],
    specs: { 'Display': 'Dual Micro-OLED', 'Resolution': '4K per eye', 'Chipset': 'Vision AI 2', 'Storage': '256GB' },
  },
  {
    id: 44,
    title: 'OmniCharge 20K Power Bank',
    description: '100W USB-C Power Delivery portable charger with smart OLED display.',
    longDescription: 'Charge your laptop, phone, and tablet simultaneously. The integrated screen displays battery percentage, wattage output, and estimated charging time in real time.',
    price: 79.99,
    image: 'https://images.unsplash.com/photo-1609592424209-dd9a2a5d157e?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1609592424209-dd9a2a5d157e?w=600&q=80',
    ],
    category: 'Electronics',
    subcategory: 'Accessories',
    rating: 4.6,
    reviewCount: 310,
    inventory: 150,
    badge: 'bestseller',
    tags: ['powerbank', 'charger', 'usb-c', 'pd'],
    specs: { 'Capacity': '20,000mAh', 'Max Output': '100W USB-C', 'Ports': '2x USB-C, 1x USB-A', 'Display': 'OLED Info' },
  },
  {
    id: 45,
    title: 'FocusOne DSLR Creator Kit',
    description: '32.5 MP Mirrorless camera with 15-45mm stabilizer lens kit.',
    longDescription: 'The perfect kit for modern creators. Offers dual pixel autofocus, uncropped 4K video recording, and custom color profiles to get instant cinematic results directly in-camera.',
    price: 1199.99,
    originalPrice: 1399.99,
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&q=80',
    ],
    category: 'Electronics',
    subcategory: 'Cameras',
    rating: 4.8,
    reviewCount: 142,
    inventory: 15,
    badge: 'sale',
    tags: ['camera', 'dslr', 'creator', 'video'],
    specs: { 'Sensor': '32.5MP APS-C', 'Video': '4K@60fps', 'Lens': '15-45mm IS STM', 'Connectivity': 'Wi-Fi, BT' },
  },
  {
    id: 46,
    title: 'Studio Mic Pro Streamer',
    description: 'Professional USB/XLR condenser microphone with RGB lighting.',
    longDescription: 'Get crisp studio broadcast audio for streaming, podcasting, and vocal recording. Equipped with an internal shock mount, pop filter, and zero-latency monitoring port.',
    price: 159.99,
    image: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=600&q=80',
    ],
    category: 'Electronics',
    subcategory: 'Audio',
    rating: 4.7,
    reviewCount: 195,
    inventory: 70,
    tags: ['microphone', 'streamer', 'usb', 'audio'],
    specs: { 'Type': 'Condenser', 'Pattern': 'Cardioid', 'Connection': 'USB-C / XLR', 'Sample Rate': '24-bit/96kHz' },
  },

  // === CLOTHING (7 to 10, 47 to 54) ===
  {
    id: 7,
    title: 'Echo Ultralight Jacket',
    description: 'Military-grade waterproof yet featherlight for urban explorers.',
    longDescription: 'Crafted from patented UltraShell 3-layer membrane, the Echo Jacket repels rain while remaining completely breathable. Packs down to the size of a water bottle, weighing just 280g.',
    price: 189.99,
    originalPrice: 249.99,
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80',
    ],
    category: 'Clothing',
    subcategory: 'Outerwear',
    rating: 4.8,
    reviewCount: 445,
    inventory: 200,
    badge: 'sale',
    tags: ['jacket', 'waterproof', 'outdoor', 'packable'],
    specs: { 'Material': 'UltraShell 3L', 'Weight': '280g', 'Waterproof': '20,000mm HH', 'Breathability': '20,000 g/m²' },
  },
  {
    id: 8,
    title: 'Nova Runner Sneakers V3',
    description: 'Biomechanically engineered for runners who demand performance.',
    longDescription: 'The Nova V3 features our Carbon Propulsion Plate technology that returns 87% of energy with every stride. CloudFoam midsole provides 40% more cushioning than traditional EVA.',
    price: 149.99,
    originalPrice: 189.99,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
    ],
    category: 'Clothing',
    subcategory: 'Footwear',
    rating: 4.9,
    reviewCount: 1203,
    inventory: 300,
    badge: 'bestseller',
    tags: ['sneakers', 'running', 'carbon', 'performance'],
    specs: { 'Plate': 'Carbon Fiber', 'Midsole': 'CloudFoam+', 'Upper': 'Flyknit 3.0', 'Drop': '8mm' },
  },
  {
    id: 9,
    title: 'Luxe Merino Wool Sweater',
    description: 'Italian superfine 18.5 micron merino — naturally warm and soft.',
    longDescription: 'Sourced from Italian wool mills, this sweater uses ultra-soft 18.5 micron Merino fibers. Naturally temperature-regulating, moisture-wicking, and odor-resistant.',
    price: 129.99,
    image: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&q=80',
    ],
    category: 'Clothing',
    subcategory: 'Tops',
    rating: 4.6,
    reviewCount: 278,
    inventory: 150,
    badge: 'new',
    tags: ['sweater', 'merino', 'wool', 'luxury'],
    specs: { 'Material': '100% Merino Wool', 'Micron': '18.5', 'Fit': 'Regular', 'Origin': 'Italy' },
  },
  {
    id: 10,
    title: 'TechFlex Performance Shorts',
    description: '4-way stretch training shorts with integrated compression liner.',
    longDescription: 'Engineered for elite training, the TechFlex shorts feature 4-directional stretch fabric. Integrated compression liner provides muscle support and prevents chafing.',
    price: 69.99,
    image: 'https://images.unsplash.com/photo-1562886877-f16cc7656a1a?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1562886877-f16cc7656a1a?w=600&q=80',
    ],
    category: 'Clothing',
    subcategory: 'Activewear',
    rating: 4.5,
    reviewCount: 334,
    inventory: 500,
    tags: ['shorts', 'training', 'compression', 'performance'],
    specs: { 'Material': 'Polyester/Elastane', 'Stretch': '4-way', 'Liner': 'Compression', 'Pockets': 'Zip pockets' },
  },
  {
    id: 47,
    title: 'Urban Explorer Backpack 30L',
    description: 'Weatherproof commuter backpack with dedicated 16" laptop vault.',
    longDescription: 'Built with Cordura ballistic nylon and waterproof zippers, this pack keeps your gear safe in all environments. Features ergonomic straps and hidden anti-theft compartments.',
    price: 119.99,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80',
    ],
    category: 'Clothing',
    subcategory: 'Accessories',
    rating: 4.8,
    reviewCount: 412,
    inventory: 140,
    badge: 'bestseller',
    tags: ['backpack', 'commuter', 'waterproof', 'accessories'],
    specs: { 'Capacity': '30L', 'Material': 'Cordura 1000D', 'Laptop Pocket': 'Up to 16"', 'Weight': '0.9kg' },
  },
  {
    id: 48,
    title: 'Vanguard Leather Jacket',
    description: 'Handcrafted top-grain black leather jacket with YKK steel hardware.',
    longDescription: 'A timeless silhouette designed to wear in beautifully. Made from top-grain cowhide leather with premium satin lining and heavy-duty metal zippers.',
    price: 299.99,
    originalPrice: 399.99,
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80',
    ],
    category: 'Clothing',
    subcategory: 'Outerwear',
    rating: 4.9,
    reviewCount: 98,
    inventory: 40,
    badge: 'hot',
    tags: ['leather', 'jacket', 'classic', 'premium'],
    specs: { 'Leather': 'Top-grain Cowhide', 'Zippers': 'YKK Metal', 'Fit': 'Slim Tailored', 'Lining': 'Satin' },
  },
  {
    id: 49,
    title: 'Signature Classic Trench Coat',
    description: 'Double-breasted cotton gabardine trench coat with water-resistant finish.',
    longDescription: 'The quintessential transitional piece. Hand-finished detailing, protective gun flaps, and adjustable belt matching modern styling parameters.',
    price: 249.99,
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80',
    ],
    category: 'Clothing',
    subcategory: 'Outerwear',
    rating: 4.7,
    reviewCount: 65,
    inventory: 30,
    badge: 'new',
    tags: ['trench', 'coat', 'classic', 'cotton'],
    specs: { 'Material': '100% Cotton Gabardine', 'Finish': 'DWR Water-resistant', 'Length': 'Mid-length', 'Origin': 'England design' },
  },
  {
    id: 50,
    title: 'Minimalist Chelsea Boots',
    description: 'Handcrafted Italian suede Chelsea boots with custom Crepe sole.',
    longDescription: 'Comfort meets elegance. Features soft calfskin lining, premium Italian waxed suede, and flexible crepe soles designed for all-day comfort.',
    price: 179.99,
    originalPrice: 219.99,
    image: 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=600&q=80',
    ],
    category: 'Clothing',
    subcategory: 'Footwear',
    rating: 4.6,
    reviewCount: 112,
    inventory: 60,
    badge: 'sale',
    tags: ['boots', 'chelsea', 'suede', 'italian'],
    specs: { 'Suede': 'Italian Calf Suede', 'Sole': 'Natural Crepe', 'Lining': 'Calfskin', 'Construction': 'Blake Stitch' },
  },
  {
    id: 51,
    title: 'AeroShell Active Windbreaker',
    description: 'Lightweight, windproof shell designed for high-intensity running.',
    longDescription: 'Made of recycled ripstop nylon, the AeroShell offers targeted back ventilation, reflective logos, and zip storage pockets for absolute convenience during cold morning runs.',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1548883354-7622d03aca27?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1548883354-7622d03aca27?w=600&q=80',
    ],
    category: 'Clothing',
    subcategory: 'Activewear',
    rating: 4.5,
    reviewCount: 88,
    inventory: 150,
    tags: ['windbreaker', 'running', 'active', 'lightweight'],
    specs: { 'Material': 'Recycled Ripstop Nylon', 'Weight': '120g', 'Windproof': 'Yes', 'Reflectors': '3M High-vis' },
  },
  {
    id: 52,
    title: 'Premium Linen Resort Shirt',
    description: 'Super-breathable 100% organic linen shirt with relaxed camp collar.',
    longDescription: 'Garment-dyed for optimal texture and softness, this resort shirt offers absolute ventilation during warm summer getaways.',
    price: 59.99,
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&q=80',
    ],
    category: 'Clothing',
    subcategory: 'Tops',
    rating: 4.7,
    reviewCount: 143,
    inventory: 180,
    badge: 'new',
    tags: ['linen', 'shirt', 'summer', 'resort'],
    specs: { 'Material': '100% Organic Linen', 'Collar': 'Camp / Resort', 'Fit': 'Relaxed', 'Button': 'Mother of Pearl' },
  },
  {
    id: 53,
    title: 'Aviator Premium Sunglasses',
    description: 'Titanium aviator sunglasses with polarization and anti-glare finish.',
    longDescription: 'Handcrafted frames using premium Japanese titanium. 100% UVA/UVB protection with double-sided scratch resistance coating.',
    price: 199.99,
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&q=80',
    ],
    category: 'Clothing',
    subcategory: 'Accessories',
    rating: 4.8,
    reviewCount: 124,
    inventory: 85,
    badge: 'bestseller',
    tags: ['sunglasses', 'polarized', 'titanium', 'accessories'],
    specs: { 'Frame': 'Japanese Titanium', 'Lens': 'Polarized TAC', 'UV Protection': '100% UVA/UVB', 'Weight': '18g' },
  },
  {
    id: 54,
    title: 'Luxury Leather Travel Wallet',
    description: 'RFID-blocking full grain leather wallet with passport sleeve.',
    longDescription: 'Hand-stitched leather designed to secure your essentials. Accommodates passports, boarding passes, currency bills, and up to 10 credit cards.',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1627124793833-dd9a2a5d157e?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1627124793833-dd9a2a5d157e?w=600&q=80',
    ],
    category: 'Clothing',
    subcategory: 'Accessories',
    rating: 4.6,
    reviewCount: 99,
    inventory: 110,
    tags: ['wallet', 'leather', 'rfid', 'travel'],
    specs: { 'Leather': 'Full-grain Horween', 'Stitching': 'Hand-waxed thread', 'RFID Protection': 'Yes', 'Capacity': '10+ cards' },
  },

  // === HOME & LIVING (11 to 15, 55 to 64) ===
  {
    id: 11,
    title: 'Lumina Arc Floor Lamp',
    description: 'Smart LED floor lamp with voice control and circadian rhythm sync.',
    longDescription: 'The Lumina Arc adjusts color temperature throughout the day to match your body\'s natural light needs. Compatible with Alexa, Google Home, and Apple HomeKit.',
    price: 249.99,
    originalPrice: 299.99,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80',
    ],
    category: 'Home',
    subcategory: 'Lighting',
    rating: 4.7,
    reviewCount: 198,
    inventory: 75,
    badge: 'smart',
    tags: ['lamp', 'smart', 'led', 'circadian'],
    specs: { 'Wattage': '30W LED', 'Color Temp': '2700K–6500K', 'Brightness': '2500lm', 'Integration': 'Alexa, HomeKit' },
  },
  {
    id: 12,
    title: 'AeroBreath Air Purifier Pro',
    description: 'True HEPA H13 + UV-C sterilization for spaces up to 80m².',
    longDescription: 'Breathe cleaner air with the AeroBreath Pro\'s 5-stage filtration system. True HEPA H13 captures 99.97% of particles as small as 0.1 microns, while UV-C sterilization destroys viruses.',
    price: 399.99,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    ],
    category: 'Home',
    subcategory: 'Appliances',
    rating: 4.8,
    reviewCount: 456,
    inventory: 90,
    badge: 'hot',
    tags: ['air-purifier', 'hepa', 'uv-c', 'smart'],
    specs: { 'Coverage': '80m²', 'Filter': 'HEPA H13 + Carbon', 'CADR': '600 m³/h', 'Noise': '18dB' },
  },
  {
    id: 13,
    title: 'BrewMaster Pro Coffee System',
    description: 'Bean-to-cup espresso with built-in grinder and milk frother.',
    longDescription: 'Elevate your morning ritual with barista-quality coffee at home. The BrewMaster Pro features a built-in conical burr grinder with 25 grind settings and a 15-bar Italian pump.',
    price: 649.99,
    originalPrice: 799.99,
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80',
    ],
    category: 'Home',
    subcategory: 'Kitchen',
    rating: 4.9,
    reviewCount: 723,
    inventory: 40,
    badge: 'bestseller',
    tags: ['coffee', 'espresso', 'grinder', 'barista'],
    specs: { 'Pressure': '15-bar Pump', 'Grinder': 'Conical Burr', 'Water Tank': '2.5L', 'Bean Hopper': '500g' },
  },
  {
    id: 14,
    title: 'Serenity Weighted Blanket',
    description: 'Premium glass bead weighted blanket for deep pressure therapy.',
    longDescription: 'Designed in collaboration with sleep scientists, the Serenity Blanket uses medical-grade micro glass beads to distribute weight evenly and improve sleep quality.',
    price: 129.99,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80',
    ],
    category: 'Home',
    subcategory: 'Bedding',
    rating: 4.7,
    reviewCount: 892,
    inventory: 180,
    tags: ['blanket', 'weighted', 'sleep', 'therapy'],
    specs: { 'Weights': '4kg-10kg', 'Fill': 'Glass Beads', 'Cover': 'Bamboo Viscose', 'Thread Count': '400TC' },
  },
  {
    id: 15,
    title: 'Chef\'s Pro Knife Set 8pc',
    description: 'German X50CrMoV15 steel, hand-balanced, lifetime guaranteed.',
    longDescription: 'German high-carbon stainless steel hand-sharpened to 15° per side. Full-tang construction with triple-riveted handles and acacia storage block.',
    price: 279.99,
    originalPrice: 349.99,
    image: 'https://images.unsplash.com/photo-1593618998160-e34014e67546?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1593618998160-e34014e67546?w=600&q=80',
    ],
    category: 'Home',
    subcategory: 'Kitchen',
    rating: 4.8,
    reviewCount: 567,
    inventory: 60,
    badge: 'sale',
    tags: ['knives', 'kitchen', 'german-steel', 'professional'],
    specs: { 'Steel': 'German X50', 'Hardness': '58 HRC', 'Pieces': '8pc Set', 'Block': 'Acacia Wood' },
  },
  {
    id: 55,
    title: 'SmartDesk Pro Standing Desk',
    description: 'Dual-motor electric sit-stand desk with bamboo tabletop.',
    longDescription: 'Transition smoothly between sitting and standing. Features quiet dual motors, anti-collision sensor, and 4 custom memory height settings.',
    price: 599.99,
    originalPrice: 699.99,
    image: 'https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?w=600&q=80',
    ],
    category: 'Home',
    subcategory: 'Furniture',
    rating: 4.8,
    reviewCount: 322,
    inventory: 40,
    badge: 'sale',
    tags: ['desk', 'standing', 'bamboo', 'office'],
    specs: { 'Height Range': '60-125cm', 'Motors': 'Dual Quiet', 'Tabletop': 'Natural Bamboo', 'Load Capacity': '125kg' },
  },
  {
    id: 56,
    title: 'ErgoChair Pro Office Chair',
    description: 'Premium mesh office chair with fully adjustable posture support.',
    longDescription: 'Features multi-adjustable headrest, custom lumbar support, lockable tilt tension mechanism, and breathable mesh designed to maximize working comfort.',
    price: 349.99,
    image: 'https://images.unsplash.com/photo-1580481072645-022f9a6dbf27?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1580481072645-022f9a6dbf27?w=600&q=80',
    ],
    category: 'Home',
    subcategory: 'Furniture',
    rating: 4.7,
    reviewCount: 451,
    inventory: 80,
    badge: 'bestseller',
    tags: ['chair', 'office', 'ergonomic', 'workspace'],
    specs: { 'Adjustments': 'Armrest, Depth, Tilt', 'Backrest': 'Breathable Mesh', 'Base': 'Polished Aluminum', 'Capacity': '135kg' },
  },
  {
    id: 57,
    title: 'Robot Vacuum Cleaner V9',
    description: 'Smart LiDAR mapping robot vacuum with integrated wet mopping.',
    longDescription: 'Completely autonomous floor cleaning. Uses LiDAR to map your home layout, avoid obstacles, and clean carpets and hard floor surfaces with 4000Pa suction power.',
    price: 389.99,
    image: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=600&q=80',
    ],
    category: 'Home',
    subcategory: 'Appliances',
    rating: 4.6,
    reviewCount: 201,
    inventory: 50,
    badge: 'hot',
    tags: ['vacuum', 'robot', 'mopping', 'lidar'],
    specs: { 'Suction': '4000Pa', 'Navigation': 'LiDAR Mapping', 'Runtime': '150 minutes', 'Dustbin': '600ml' },
  },
  {
    id: 58,
    title: 'Minimalist Bedside Organizer Lamp',
    description: 'Modern ash wood bedside table lamp with wireless Qi charger.',
    longDescription: 'Combines warm adjustable glow with utility. Houses a built-in wireless fast-charging pad and premium fabric lamp shade.',
    price: 79.99,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80',
    ],
    category: 'Home',
    subcategory: 'Lighting',
    rating: 4.8,
    reviewCount: 310,
    inventory: 120,
    badge: 'new',
    tags: ['lamp', 'wireless-charger', 'bedside', 'wood'],
    specs: { 'Base': 'Natural Ash Wood', 'Charging': '15W Qi Wireless', 'Bulb': 'Warm LED Included', 'Port': 'USB charging output' },
  },
  {
    id: 59,
    title: 'Smart Keyless Door Lock',
    description: 'Fingerprint, passcode, and app-controlled deadbolt lock with Wi-Fi.',
    longDescription: 'Secure your entry points. Stores up to 100 fingerprints, generates temporary guest passcodes, and alerts you of any forced entry attempts.',
    price: 199.99,
    originalPrice: 249.99,
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1558002038-1055907df827?w=600&q=80',
    ],
    category: 'Home',
    subcategory: 'Security',
    rating: 4.7,
    reviewCount: 167,
    inventory: 45,
    badge: 'sale',
    tags: ['doorlock', 'smart-home', 'security', 'fingerprint'],
    specs: { 'Entry Methods': 'Fingerprint, PIN, App', 'Battery': '4x AA (1 year)', 'Wireless': 'Wi-Fi Built-in', 'Lock Type': 'Deadbolt' },
  },
  {
    id: 60,
    title: 'Handwoven Rattan Pendant Light',
    description: 'Natural organic rattan dome pendant lamp for dining rooms.',
    longDescription: 'Each piece is handwoven by local artisans. Creates warm, beautiful light shadows and lends an organic, cozy atmosphere to any modern dining setting.',
    price: 119.99,
    image: 'https://images.unsplash.com/photo-1513506003901-1e6a35af4a48?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1513506003901-1e6a35af4a48?w=600&q=80',
    ],
    category: 'Home',
    subcategory: 'Lighting',
    rating: 4.5,
    reviewCount: 94,
    inventory: 60,
    tags: ['pendant-light', 'rattan', 'handwoven', 'dining'],
    specs: { 'Material': 'Natural Rattan', 'Diameter': '45cm', 'Cord Length': '1.5m Adjustable', 'Socket': 'E27 max 60W' },
  },
  {
    id: 61,
    title: 'Velvet Accent Armchair',
    description: 'Elegant velvet upholstered armchair with gold-tipped metal legs.',
    longDescription: 'Sink into ultimate comfort. Combining thick high-density foam padding with a sturdy steel frame and premium stain-resistant velvet fabric.',
    price: 279.99,
    image: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&q=80',
    ],
    category: 'Home',
    subcategory: 'Furniture',
    rating: 4.7,
    reviewCount: 104,
    inventory: 25,
    badge: 'new',
    tags: ['chair', 'armchair', 'velvet', 'living-room'],
    specs: { 'Fabric': 'Stain-resistant Velvet', 'Legs': 'Steel with Gold Finish', 'Weight Capacity': '150kg', 'Seat Height': '42cm' },
  },
  {
    id: 62,
    title: 'AeroPress Custom Tea Set',
    description: 'Tempered borosilicate glass teapot with custom micro-mesh infuser.',
    longDescription: 'Brew beautiful loose leaf teas. Holds up to 1.2L of warm herbal blend, heat-resistant handle, and dripping-free spout design.',
    price: 49.99,
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&q=80',
    ],
    category: 'Home',
    subcategory: 'Kitchen',
    rating: 4.6,
    reviewCount: 142,
    inventory: 90,
    tags: ['teapot', 'tea', 'glass', 'infuser'],
    specs: { 'Capacity': '1.2L', 'Material': 'Borosilicate Glass', 'Infuser': '304 Stainless Steel', 'Stove Safe': 'Yes' },
  },
  {
    id: 63,
    title: 'Pure Bamboo Luxury Sheet Set',
    description: '100% bamboo viscose sheets, silky soft, naturally cooling.',
    longDescription: 'The ultimate sleep experience. Temperature regulating sheets with extra-deep pockets to fit any modern mattress height securely.',
    price: 139.99,
    originalPrice: 169.99,
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&q=80',
    ],
    category: 'Home',
    subcategory: 'Bedding',
    rating: 4.8,
    reviewCount: 284,
    inventory: 80,
    badge: 'sale',
    tags: ['sheets', 'bamboo', 'bedding', 'cooling'],
    specs: { 'Material': '100% Bamboo Viscose', 'Thread Count': '300TC (equivalent to 1000TC cotton)', 'Pockets': '40cm Deep', 'Includes': '1 Flat, 1 Fitted, 2 Pillowcases' },
  },
  {
    id: 64,
    title: 'Ceramic Organic Vase Set',
    description: 'Trio of hand-painted matte ceramic vases in earth tones.',
    longDescription: 'Elevate your mantelpiece or shelf. Features three distinct organic shapes and finishes designed to display dry botanicals beautifully.',
    price: 69.99,
    image: 'https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=600&q=80',
    ],
    category: 'Home',
    subcategory: 'Decor',
    rating: 4.7,
    reviewCount: 78,
    inventory: 110,
    tags: ['vases', 'ceramic', 'decor', 'minimalist'],
    specs: { 'Material': 'Matte Ceramic', 'Sizes': '24cm, 18cm, 12cm', 'Finishes': 'Textured Earthy', 'Waterproof': 'Dry use recommended' },
  },

  // === SPORTS & FITNESS (16 to 18, 22, 65 to 74) ===
  {
    id: 16,
    title: 'PowerRack Elite Home Gym',
    description: 'Commercial-grade 4-post rack with 1000kg capacity and cable system.',
    longDescription: 'Build your dream home gym. Constructed from 11-gauge steel with a powder-coated finish. Includes functional trainer and adjustable safety arms.',
    price: 2499.99,
    originalPrice: 2999.99,
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&q=80',
    ],
    category: 'Sports',
    subcategory: 'Fitness Equipment',
    rating: 4.9,
    reviewCount: 234,
    inventory: 15,
    badge: 'hot',
    tags: ['gym', 'rack', 'home-gym', 'strength'],
    specs: { 'Capacity': '1000kg', 'Steel': '11-Gauge', 'Cable System': 'Dual 200lb stacks', 'Footprint': '240x150cm' },
  },
  {
    id: 17,
    title: 'TrailBlaze MTB Bike 29"',
    description: 'Full suspension carbon mountain bike for trail dominance.',
    longDescription: 'The TrailBlaze features a full carbon fiber frame, front and rear 130mm suspension, and SRAM GX Eagle 12-speed drivetrain.',
    price: 3299.99,
    image: 'https://images.unsplash.com/photo-1544192240-4a34feb0104c?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1544192240-4a34feb0104c?w=600&q=80',
    ],
    category: 'Sports',
    subcategory: 'Cycling',
    rating: 4.8,
    reviewCount: 156,
    inventory: 12,
    badge: 'new',
    tags: ['bike', 'mtb', 'carbon', 'full-suspension'],
    specs: { 'Frame': 'Carbon Fiber', 'Travel': '130mm', 'Drivetrain': 'SRAM 12-speed', 'Wheel Size': '29 inches' },
  },
  {
    id: 18,
    title: 'EliteSwim Wetsuit Pro',
    description: 'Yamamoto #40 neoprene for maximum speed and buoyancy.',
    longDescription: 'Trusted by triathletes worldwide. Features Yamamoto #40 neoprene with strategically placed buoyancy panels and flexible shoulders.',
    price: 549.99,
    originalPrice: 649.99,
    image: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=600&q=80',
    ],
    category: 'Sports',
    subcategory: 'Swimming',
    rating: 4.7,
    reviewCount: 89,
    inventory: 40,
    badge: 'sale',
    tags: ['wetsuit', 'triathlon', 'swimming', 'neoprene'],
    specs: { 'Material': 'Yamamoto #40', 'Buoyancy': 'Zoned 5/3mm', 'Zipper': 'YKK Titanium', 'Seams': 'Glued & Blindstitched' },
  },
  {
    id: 22,
    title: 'TheraPulse Massage Gun Pro',
    description: 'Professional percussive therapy with 6 heads and 5 speed modes.',
    longDescription: 'High-amplitude percussion helps accelerate muscle recovery. Brushless quiet motor with up to 5 hours of continuous battery life.',
    price: 199.99,
    originalPrice: 249.99,
    image: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=600&q=80',
    ],
    category: 'Sports',
    subcategory: 'Recovery',
    rating: 4.7,
    reviewCount: 789,
    inventory: 130,
    badge: 'hot',
    tags: ['massage-gun', 'recovery', 'physiotherapy', 'percussion'],
    specs: { 'Percussions': '3200 RPM max', 'Amplitude': '12.7mm', 'Stall Force': '60lbs', 'Battery': '5 hours' },
  },
  {
    id: 65,
    title: 'Carbon Road Bike Racer',
    description: 'Aerodynamic carbon frame road racer with Shimano Ultegra Di2.',
    longDescription: 'Built for speed and flat-out racing. Electronic shifting, carbon wheelset, and integrated cabling reduce drag to absolute minimums.',
    price: 4599.99,
    image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=600&q=80',
    ],
    category: 'Sports',
    subcategory: 'Cycling',
    rating: 4.9,
    reviewCount: 42,
    inventory: 5,
    badge: 'new',
    tags: ['road-bike', 'shimano', 'carbon', 'electronic-shifting'],
    specs: { 'Frame': 'T800 Carbon Aero', 'Gears': 'Shimano Ultegra Di2 2x12', 'Wheelset': '45mm Carbon Tubeless', 'Weight': '7.2kg' },
  },
  {
    id: 66,
    title: 'Adjustable Dumbbell Set (Pair)',
    description: 'Heavy adjustable steel dumbbells replacing 15 weight pairs.',
    longDescription: 'Dial mechanism allows immediate weight selections from 2kg to 24kg per dumbbell. Space-saving fitness gear at its best.',
    price: 299.99,
    originalPrice: 349.99,
    image: 'https://images.unsplash.com/photo-1638536532686-d610adfc8e5c?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1638536532686-d610adfc8e5c?w=600&q=80',
    ],
    category: 'Sports',
    subcategory: 'Fitness Equipment',
    rating: 4.8,
    reviewCount: 312,
    inventory: 90,
    badge: 'sale',
    tags: ['dumbbells', 'adjustable', 'strength', 'home-gym'],
    specs: { 'Weight Range': '2kg - 24kg each', 'Plates': 'Coated Steel', 'Adjustment': 'Quick-turn Dial', 'Stand Included': 'No' },
  },
  {
    id: 67,
    title: 'Elite Yoga Mat Pro',
    description: 'Natural rubber yoga mat with alignment grid and non-slip grip.',
    longDescription: 'High-density cushioning protects joints. The textured natural rubber base provides absolute anti-slip security during hot yoga sessions.',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600&q=80',
    ],
    category: 'Sports',
    subcategory: 'Yoga',
    rating: 4.7,
    reviewCount: 184,
    inventory: 140,
    badge: 'bestseller',
    tags: ['yoga', 'mat', 'non-slip', 'natural-rubber'],
    specs: { 'Material': 'Natural Rubber + PU', 'Dimensions': '183 x 68 cm', 'Thickness': '4.5mm', 'Grid': 'Laser Etched alignment' },
  },
  {
    id: 68,
    title: '4-Person Geodesic Camping Tent',
    description: '4-season weatherproof tent with double layer vestibules.',
    longDescription: 'Built to withstand storm winds and heavy snowfall. Features DAC aluminum poles, ripstop nylon canopy, and dual entries.',
    price: 349.99,
    image: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&q=80',
    ],
    category: 'Sports',
    subcategory: 'Outdoor',
    rating: 4.8,
    reviewCount: 96,
    inventory: 20,
    badge: 'new',
    tags: ['tent', 'camping', 'weatherproof', 'outdoor'],
    specs: { 'Capacity': '4 Persons', 'Seasons': '4-season', 'Poles': 'DAC Pressfit Aluminum', 'Weight': '3.8kg' },
  },
  {
    id: 69,
    title: 'Insulated Titanium Mug 450ml',
    description: 'Double-walled camping mug with folding handles and lid.',
    longDescription: 'Extremely lightweight, corrosion resistant, and preserves hot beverages. Mesh storage bag included for absolute packability.',
    price: 39.99,
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&q=80',
    ],
    category: 'Sports',
    subcategory: 'Outdoor',
    rating: 4.6,
    reviewCount: 145,
    inventory: 200,
    tags: ['mug', 'titanium', 'camping', 'backpacking'],
    specs: { 'Material': 'Pure Grade 1 Titanium', 'Capacity': '450ml', 'Walls': 'Double-walled vacuum', 'Weight': '98g' },
  },
  {
    id: 70,
    title: 'Performance GPS Cycle Computer',
    description: 'Color map navigation cycle computer with heart rate strap.',
    longDescription: 'Tracks speed, routing, altitude, and training stress score. Integrates seamlessly with Strava, Shimano Di2, and smart trainers.',
    price: 299.99,
    image: 'https://images.unsplash.com/photo-1544192240-4a34feb0104c?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1544192240-4a34feb0104c?w=600&q=80',
    ],
    category: 'Sports',
    subcategory: 'Cycling',
    rating: 4.7,
    reviewCount: 110,
    inventory: 35,
    badge: 'sale',
    tags: ['cycling', 'gps', 'strava', 'navigation'],
    specs: { 'Display': '2.6" Color Touch', 'Sensors': 'GPS, Glonass, Barometer', 'Battery Life': '20 hours', 'Weight': '80g' },
  },
  {
    id: 71,
    title: 'Premium Recovery Compression Boots',
    description: 'Sequential air compression leg sleeves for muscle recovery.',
    longDescription: 'Enhance blood flow and reduce muscle swelling post workout. Features 4 inflation chambers and adjustable zone pressure.',
    price: 499.99,
    image: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=600&q=80',
    ],
    category: 'Sports',
    subcategory: 'Recovery',
    rating: 4.8,
    reviewCount: 54,
    inventory: 15,
    badge: 'hot',
    tags: ['compression', 'recovery', 'boots', 'athletes'],
    specs: { 'Chambers': '4 Sequential', 'Pressure': '20-120 mmHg', 'Runtime': '3 hours (rechargeable)', 'Modes': '3 recovery patterns' },
  },
  {
    id: 72,
    title: 'Anti-Fog Swim Goggles Pro',
    description: 'Wide-angle polarized swim goggles with UV protection.',
    longDescription: 'Provides crystal clear peripheral vision in outdoor pools. Built with soft liquid silicone gaskets for leak-free, custom seal.',
    price: 29.99,
    image: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=600&q=80',
    ],
    category: 'Sports',
    subcategory: 'Swimming',
    rating: 4.5,
    reviewCount: 221,
    inventory: 300,
    tags: ['goggles', 'swimming', 'anti-fog', 'polarized'],
    specs: { 'Lens': 'Polarized Polycarbonate', 'UV Protection': '100%', 'Gasket': 'Liquid Silicone', 'Strap': 'Double quick-adjust' },
  },
  {
    id: 73,
    title: 'Hydration Backpack 2.5L',
    description: 'Minimalist running vest with integrated BPA-free water bladder.',
    longDescription: 'Designed for marathon runners and trail explorers. Offers elastic chest pockets for energy gels, phone, and soft flasks.',
    price: 69.99,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80',
    ],
    category: 'Sports',
    subcategory: 'Outdoor',
    rating: 4.6,
    reviewCount: 132,
    inventory: 95,
    badge: 'bestseller',
    tags: ['running', 'vest', 'hydration', 'backpack'],
    specs: { 'Bladder': '2.5L BPA-free', 'Volume': '6L Total cargo', 'Weight': '320g (empty)', 'Sizes': 'Adjustable chest straps' },
  },
  {
    id: 74,
    title: 'Dry Bag Waterproof 20L',
    description: 'Heavy duty PVC roll-top bag for rafting and marine sports.',
    longDescription: 'Completely submersible water protection. Features welded seams and comfortable removable backpack straps.',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
    ],
    category: 'Sports',
    subcategory: 'Swimming',
    rating: 4.7,
    reviewCount: 175,
    inventory: 240,
    tags: ['dry-bag', 'waterproof', 'rafting', 'outdoor'],
    specs: { 'Capacity': '20L', 'Material': '500D PVC Tarpaulin', 'Seams': 'High-frequency Welded', 'Closure': 'Roll-top buckle' },
  },

  // === BEAUTY & WELLNESS (19 to 20, 75 to 90) ===
  {
    id: 19,
    title: 'Glow Pro LED Face Mask',
    description: 'Medical-grade LED light therapy with 7 wavelengths for skin.',
    longDescription: 'Achieve spa-quality skin rejuvenation from home. 7 LED wavelengths target collagen production, acne elimination, and tissue regeneration.',
    price: 299.99,
    originalPrice: 399.99,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80',
    ],
    category: 'Beauty',
    subcategory: 'Skincare',
    rating: 4.6,
    reviewCount: 634,
    inventory: 85,
    badge: 'hot',
    tags: ['led', 'skincare', 'face-mask', 'anti-aging'],
    specs: { 'Wavelengths': '7 Colors', 'LEDs': '150 Medical-grade', 'Time': '10-20 mins session', 'Integration': 'Wireless remote' },
  },
  {
    id: 20,
    title: 'Aura Ultrasonic Diffuser Set',
    description: 'Premium ultrasonic aromatherapy with 7-color ambient lighting.',
    longDescription: 'Ultrasonic technology breaks essential oils into a cool, fine mist without heat, preserving their therapeutic properties.',
    price: 79.99,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&q=80',
    ],
    category: 'Beauty',
    subcategory: 'Wellness',
    rating: 4.5,
    reviewCount: 412,
    inventory: 200,
    tags: ['diffuser', 'aromatherapy', 'essential-oils', 'wellness'],
    specs: { 'Capacity': '500ml', 'Runtime': '12 hours max', 'LED': '7-color cycle', 'Mist Output': '35ml/h' },
  },
  {
    id: 75,
    title: 'Advanced Retinol Skin Complex',
    description: '2.5% pure encapsulated retinol serum with hyaluronic acid.',
    longDescription: 'Targets fine lines, dark spots, and skin texture. Slow-release encapsulation minimizes irritation, while squalane and jojoba oil soothe the barrier.',
    price: 59.99,
    originalPrice: 69.99,
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80',
    ],
    category: 'Beauty',
    subcategory: 'Skincare',
    rating: 4.8,
    reviewCount: 521,
    inventory: 180,
    badge: 'bestseller',
    tags: ['retinol', 'serum', 'anti-aging', 'skincare'],
    specs: { 'Active Retinol': '2.5% Encapsulated', 'Volume': '30ml / 1 fl. oz', 'Skin Type': 'All except sensitive', 'Packaging': 'UV-protective dropper' },
  },
  {
    id: 76,
    title: 'Sonic Facial Cleansing Brush',
    description: 'Waterproof silicone sonic face massager and pore deep-cleanser.',
    longDescription: 'Delivers 8000 T-Sonic pulsations per minute. Made of ultra-hygienic non-porous silicone designed to gently exfoliate dead skin.',
    price: 119.99,
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&q=80',
    ],
    category: 'Beauty',
    subcategory: 'Skincare',
    rating: 4.7,
    reviewCount: 310,
    inventory: 90,
    badge: 'new',
    tags: ['sonic-brush', 'cleansing', 'waterproof', 'silicone'],
    specs: { 'Pulsations': '8000 / min', 'Intensity Levels': '12 settings', 'Waterproof': 'IPX7 rating', 'Battery': 'Rechargeable (300 uses)' },
  },
  {
    id: 77,
    title: 'Hydrating Botanical Body Wash',
    description: 'Sulfates-free organic shower gel infused with lavender and amber oil.',
    longDescription: 'Hydrates while gently cleansing the skin. pH-balanced formula enriched with natural aloe vera juice and organic chamomile extract.',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&q=80',
    ],
    category: 'Beauty',
    subcategory: 'Wellness',
    rating: 4.5,
    reviewCount: 421,
    inventory: 350,
    tags: ['bodywash', 'organic', 'lavender', 'sulfate-free'],
    specs: { 'Volume': '500ml', 'pH Level': '5.5 Balanced', 'Scent': 'Lavender & Sweet Amber', 'Sulfate-free': 'Yes' },
  },
  {
    id: 78,
    title: 'Premium Rose Quartz Roller Set',
    description: 'Double-sided gua sha and face roller made from Brazilian quartz.',
    longDescription: 'Promotes lymphatic drainage and increases microcirculation. Natural cold stone reduces puffiness and relaxes facial muscles.',
    price: 34.99,
    image: 'https://images.unsplash.com/photo-1617897903246-719242758050?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1617897903246-719242758050?w=600&q=80',
    ],
    category: 'Beauty',
    subcategory: 'Skincare',
    rating: 4.6,
    reviewCount: 198,
    inventory: 160,
    badge: 'sale',
    tags: ['guasha', 'quartz', 'roller', 'massage'],
    specs: { 'Material': '100% Brazilian Rose Quartz', 'Frame': 'Noise-free zinc alloy', 'Kit Includes': '1x Roller, 1x Gua Sha, pouch', 'Certificates': 'Ethically Sourced' },
  },
  {
    id: 79,
    title: 'Maison Noir Luxury Perfume',
    description: 'Unisex eau de parfum with notes of sandalwood, cardamon, and oud.',
    longDescription: 'A bold, sophisticated fragrance profile. Exceptional sillage and long lasting power of up to 10 hours on fabric and skin.',
    price: 149.99,
    originalPrice: 189.99,
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1541643600914-78b084683601?w=600&q=80',
    ],
    category: 'Beauty',
    subcategory: 'Fragrance',
    rating: 4.8,
    reviewCount: 88,
    inventory: 50,
    badge: 'hot',
    tags: ['perfume', 'luxury', 'unisex', 'sandalwood'],
    specs: { 'Type': 'Eau de Parfum', 'Volume': '100ml / 3.4 oz', 'Notes': 'Sandalwood, Cardamon, Oud', 'Longevity': 'Up to 10 hours' },
  },
  {
    id: 80,
    title: 'Argan Oil Repair Hair Mask',
    description: 'Deep conditioning treatment for damaged and dry hair.',
    longDescription: 'Reconstructs hair fibers with pure Moroccan argan oil, keratin, and silk proteins. Free from parabens and silicones.',
    price: 29.99,
    image: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=600&q=80',
    ],
    category: 'Beauty',
    subcategory: 'Haircare',
    rating: 4.7,
    reviewCount: 387,
    inventory: 200,
    badge: 'bestseller',
    tags: ['hairmask', 'argan-oil', 'keratin', 'repair'],
    specs: { 'Volume': '250ml', 'Active Ingredient': 'Moroccan Argan Oil', 'Hair Type': 'Dry/Damaged', 'Paraben-free': 'Yes' },
  },
  {
    id: 81,
    title: 'Mineral Protection SPF 50+',
    description: 'Broad spectrum matte physical sunscreen with zinc oxide.',
    longDescription: 'Defends skin against UVA and UVB rays without leaving a white cast. Infused with niacinamide to help calm redness.',
    price: 32.99,
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80',
    ],
    category: 'Beauty',
    subcategory: 'Skincare',
    rating: 4.6,
    reviewCount: 442,
    inventory: 150,
    tags: ['sunscreen', 'mineral', 'spf50', 'zinc-oxide'],
    specs: { 'Sunscreen Type': 'Physical / Mineral', 'SPF Rating': 'SPF 50+ PA++++', 'Zinc Oxide': '20%', 'Volume': '50ml' },
  },
  {
    id: 82,
    title: 'Vitamin C Brightening Serum',
    description: '15% pure L-ascorbic acid serum with vitamin E and ferulic acid.',
    longDescription: 'Boosts radiance and reduces hyperpigmentation. Fast-absorbing water-like serum designed to neutralize daily environmental oxidative stress.',
    price: 49.99,
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80',
    ],
    category: 'Beauty',
    subcategory: 'Skincare',
    rating: 4.8,
    reviewCount: 512,
    inventory: 140,
    badge: 'new',
    tags: ['vitaminc', 'brightening', 'serum', 'anti-oxidant'],
    specs: { 'Vitamin C': '15% L-Ascorbic Acid', 'Ferulic Acid': '0.5%', 'Volume': '30ml', 'Packaging': 'Airless amber bottle' },
  },
  {
    id: 83,
    title: 'Sonic Toothbrush Ultimate',
    description: 'Electric toothbrush with 40,000 vibrations/min and wireless stand.',
    longDescription: 'Dramatically improves gum health and removes plaque. Features 5 cleaning modes and a smart 2-minute interval timer.',
    price: 89.99,
    originalPrice: 119.99,
    image: 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=600&q=80',
    ],
    category: 'Beauty',
    subcategory: 'Wellness',
    rating: 4.7,
    reviewCount: 221,
    inventory: 110,
    badge: 'sale',
    tags: ['toothbrush', 'sonic', 'hygiene', 'dental'],
    specs: { 'Frequency': '40,000 VPM', 'Modes': 'Clean, White, Polish, Gum Care, Sensitive', 'Battery': 'Up to 30 days', 'Brushing Sensor': 'Pressure Indicator' },
  },
  {
    id: 84,
    title: 'Organic Herbal Sleep Drops',
    description: 'Valerian root and chamomile liquid sleep aid formulation.',
    longDescription: 'Supports natural healthy sleep cycles. Certified organic botanical formula designed to promote deep nighttime muscle and mind relaxation.',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&q=80',
    ],
    category: 'Beauty',
    subcategory: 'Wellness',
    rating: 4.5,
    reviewCount: 167,
    inventory: 230,
    tags: ['sleep', 'supplement', 'botanical', 'drops'],
    specs: { 'Volume': '50ml', 'Active Botanicals': 'Valerian, Chamomile, Passionflower', 'Form': 'Liquid Dropper', 'Organic': 'Yes' },
  },
  {
    id: 85,
    title: 'Matte Liquid Lipstick Trio',
    description: 'Set of 3 long-wearing smudge-proof matte liquid lipsticks.',
    longDescription: 'Intense pigment loaded with nourishing vitamin E. Weightless comfort formula that guarantees flawless matte look for up to 12 hours.',
    price: 39.99,
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600&q=80',
    ],
    category: 'Beauty',
    subcategory: 'Cosmetics',
    rating: 4.6,
    reviewCount: 198,
    inventory: 140,
    badge: 'new',
    tags: ['lipstick', 'matte', 'lipkit', 'makeup'],
    specs: { 'Shades': 'Nude, Mauve, Crimson', 'Wear Time': '12 Hours', 'Volume': '3x 4ml', 'Cruelty-free': 'Yes' },
  },
  {
    id: 86,
    title: 'Nourishing Cuticle & Nail Oil',
    description: 'Sweet almond and jojoba oil blend for strong healthy nails.',
    longDescription: 'Hydrates dry cuticles and prevents nail splitting. Rich in Vitamin E and antioxidants with a quick absorbing dropper finish.',
    price: 19.99,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&q=80',
    ],
    category: 'Beauty',
    subcategory: 'Wellness',
    rating: 4.7,
    reviewCount: 143,
    inventory: 280,
    tags: ['nails', 'cuticle-oil', 'almond', 'jojoba'],
    specs: { 'Volume': '15ml', 'Key Oils': 'Sweet Almond, Jojoba, Tea Tree', 'Absorption': 'Rapid, non-greasy', 'Cruelty-free': 'Yes' },
  }
];

export const categories = [
  { name: 'All', icon: '', count: products.length },
  { name: 'Electronics', icon: '', count: products.filter(p => p.category === 'Electronics').length },
  { name: 'Clothing', icon: '', count: products.filter(p => p.category === 'Clothing').length },
  { name: 'Home', icon: '', count: products.filter(p => p.category === 'Home').length },
  { name: 'Sports', icon: '', count: products.filter(p => p.category === 'Sports').length },
  { name: 'Beauty', icon: '', count: products.filter(p => p.category === 'Beauty').length },
];

export const getProductById = (id: number): Product | undefined =>
  products.find(p => p.id === id);

export const getProductsByCategory = (category: string): Product[] =>
  category === 'All' ? products : products.filter(p => p.category === category);

export const getRelatedProducts = (product: Product, limit = 4): Product[] =>
  products.filter(p => p.id !== product.id && p.category === product.category).slice(0, limit);

export const getFeaturedProducts = (limit = 8): Product[] =>
  products.filter(p => p.badge).slice(0, limit);

export const searchProducts = (query: string): Product[] => {
  const q = query.toLowerCase();
  return products.filter(p =>
    p.title.toLowerCase().includes(q) ||
    p.description.toLowerCase().includes(q) ||
    p.tags.some(t => t.includes(q)) ||
    p.category.toLowerCase().includes(q)
  );
};
