'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';
import { getProductTranslation } from '@/lib/product_translations';


export type Language = 'en' | 'uk' | 'es' | 'de';

type Translations = Record<string, string>;

const translations: Record<Language, Translations> = {
  en: {
    // Navbar & Common
    home: 'Home',
    shop: 'Shop',
    deals: 'Deals',
    wishlist: 'Wishlist',
    compare: 'Compare',
    cart: 'Cart',
    profile: 'Profile',
    my_profile: 'My Profile',
    logout: 'Log Out',
    search_placeholder: 'Search products, brands...',
    free_shipping_hint: 'Add ${price} more for Free Shipping',
    
    // Auth Gate
    welcome_back: 'Welcome back',
    create_account: 'Create your account',
    auth_required: 'Registration is required to access Zenith Store',
    full_name: 'Full Name',
    email_address: 'Email Address',
    password: 'Password',
    sign_in: 'Sign In',
    register: 'Register',
    already_have_acc: 'Already have an account?',
    dont_have_acc: 'Don\'t have an account yet?',
    register_now: 'Register Now',
    sign_in_now: 'Sign In',
    processing: 'Processing...',

    // Wishlist Page
    my_wishlist: 'My Wishlist',
    clear_wishlist: 'Clear Wishlist',
    items_saved: 'items saved',
    wishlist_empty: 'Your wishlist is empty',
    wishlist_empty_sub: 'Save items you love here to find them easily later.',
    explore_shop: 'Explore Shop',

    // Compare Page
    compare_products: 'Compare Products',
    clear_all: 'Clear All',
    items_selected: 'items selected',
    no_compare: 'No products to compare',
    no_compare_sub: 'Add up to 4 items from the shop catalog to compare them side by side.',
    features: 'Features',
    price: 'Price',
    category: 'Category',
    rating: 'Rating',
    status: 'Status',
    description: 'Description',
    in_stock: 'In Stock',
    out_of_stock: 'Out of Stock',
    add_to_cart: 'Add to Cart',
    added_to_cart: 'Added to Cart',
    remove: 'Remove',

    // Cart Page
    your_cart: 'Your Shopping Cart',
    items_in_cart: 'items in cart',
    cart_empty: 'Your cart is empty',
    cart_empty_sub: 'Looks like you haven\'t added anything to your cart yet.',
    continue_shopping: 'Continue Shopping',
    order_summary: 'Order Summary',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    free: 'Free',
    tax: 'Estimated Tax',
    total: 'Total',
    proceed_checkout: 'Proceed to Checkout',

    // Catalog & Filters
    filters: 'Filters',
    clear_filters: 'Clear Filters',
    search: 'Search',
    price_range: 'Price Range',
    min_rating: 'Min Rating',
    in_stock_only: 'In Stock Only',
    sort_by: 'Sort',
    showing: 'Showing',
    of: 'of',
    products: 'products',
    no_products: 'No products found',
    no_products_sub: 'Try adjusting your filters',
    
    // Sort Options
    sort_featured: 'Featured',
    sort_price_asc: 'Price: Low to High',
    sort_price_desc: 'Price: High to Low',
    sort_rating: 'Best Rated',
    sort_newest: 'Newest First',

    // Category translations
    category_all: 'All',
    category_electronics: 'Electronics',
    category_clothing: 'Clothing',
    category_home: 'Home',
    category_sports: 'Sports',
    category_beauty: 'Beauty',

    // Subcategory translations
    subcategory_laptops: 'Laptops',
    subcategory_audio: 'Audio',
    subcategory_wearables: 'Wearables',
    subcategory_monitors: 'Monitors',
    subcategory_cameras: 'Cameras',
    subcategory_accessories: 'Accessories',
    subcategory_vr: 'VR',
    subcategory_outerwear: 'Outerwear',
    subcategory_footwear: 'Footwear',
    subcategory_tops: 'Tops',
    subcategory_activewear: 'Activewear',
    subcategory_lighting: 'Lighting',
    subcategory_appliances: 'Appliances',
    subcategory_kitchen: 'Kitchen',
    subcategory_bedding: 'Bedding',
    subcategory_furniture: 'Furniture',
    subcategory_security: 'Security',
    subcategory_decor: 'Decor',
    subcategory_fitness_equipment: 'Fitness Equipment',
    subcategory_cycling: 'Cycling',
    subcategory_swimming: 'Swimming',
    subcategory_recovery: 'Recovery',
    subcategory_yoga: 'Yoga',
    subcategory_outdoor: 'Outdoor',
    subcategory_skincare: 'Skincare',
    subcategory_wellness: 'Wellness',
    subcategory_fragrance: 'Fragrance',
    subcategory_haircare: 'Haircare',
    subcategory_cosmetics: 'Cosmetics',

    // Spec key translations
    spec_cpu: 'CPU',
    spec_ram: 'RAM',
    spec_storage: 'Storage',
    spec_display: 'Display',
    spec_driver: 'Driver',
    spec_anc: 'ANC',
    spec_battery: 'Battery',
    spec_connectivity: 'Connectivity',
    spec_case: 'Case',
    spec_health: 'Health Metrics',
    spec_resolution: 'Resolution',
    spec_refresh_rate: 'Refresh Rate',
    spec_panel: 'Panel Type',
    spec_hdr: 'HDR Support',
    spec_video: 'Video Mode',
    spec_stabilization: 'Stabilization',
    spec_waterproof: 'Waterproof Depth',
    spec_screen: 'Screen Size',
    spec_channels: 'Sound Channels',
    spec_power: 'Total Power',
    spec_subwoofer: 'Subwoofer Size',
    spec_material: 'Material',
    spec_weight: 'Weight',
    spec_breathability: 'Breathability',
    spec_plate: 'Propulsion Plate',
    spec_midsole: 'Midsole Technology',
    spec_upper: 'Upper Material',
    spec_drop: 'Heel Drop',
    spec_fit: 'Product Fit',
    spec_origin: 'Made In',
    spec_stretch: 'Material Stretch',
    spec_liner: 'Integrated Liner',
    spec_pockets: 'Pocket Design',
    spec_wattage: 'Bulb Wattage',
    spec_color_temp: 'Color Temp',
    spec_brightness: 'Max Brightness',
    spec_integration: 'Smart Assistant',
    spec_coverage: 'Room Coverage',
    spec_filter: 'Filter Layers',
    spec_cadr: 'Clean Air CADR',
    spec_noise: 'Operating Noise',
    spec_pressure: 'Pump Pressure',
    spec_grinder: 'Coffee Grinder',
    spec_water_tank: 'Water Tank Size',
    spec_bean_hopper: 'Bean Hopper Size',
    spec_weights: 'Available Weights',
    spec_fill: 'Internal Fill',
    spec_cover: 'Removable Cover',
    spec_thread_count: 'Thread Count',
    spec_steel: 'Steel Type',
    spec_hardness: 'Blade Hardness',
    spec_pieces: 'Set Pieces',
    spec_block: 'Storage Block',
    spec_height_range: 'Desk Height Range',
    spec_motors: 'Lifting Motors',
    spec_tabletop: 'Tabletop Material',
    spec_load_capacity: 'Weight Capacity',
    spec_adjustments: 'Adjustments Available',
    spec_backrest: 'Backrest Design',
    spec_base: 'Base Construction',
    spec_suction: 'Suction Force',
    spec_navigation: 'Navigation System',
    spec_runtime: 'Max Runtime',
    spec_dustbin: 'Dustbin Capacity',
    spec_charging: 'Qi Charging Power',
    spec_bulb: 'LED Bulb Details',
    spec_port: 'Power Output Ports',
    spec_entry_methods: 'Unlock Methods',
    spec_lock_type: 'Lock Design',
    spec_diameter: 'Lampshade Diameter',
    spec_cord_length: 'Power Cord Length',
    spec_socket: 'Lamp Socket Type',
    spec_fabric: 'Fabric Materials',
    spec_legs: 'Leg Materials',
    spec_seat_height: 'Seat Height Level',
    spec_capacity: 'Total Volume',
    spec_infuser: 'Infuser Filter Design',
    spec_stove_safe: 'Stove Safe Details',
    spec_includes: 'Items Included',
    spec_sizes: 'Sizes Available',
    spec_finishes: 'Vase Finishes',
    spec_cable_system: 'Cable System Stacks',
    spec_footprint: 'Floor Space Footprint',
    spec_travel: 'Suspension Travel',
    spec_drivetrain: 'Gear Drivetrain',
    spec_wheel_size: 'Wheel Diameter',
    spec_buoyancy: 'Neoprene Buoyancy',
    spec_seams: 'Seam Construction',
    spec_percussions: 'Percussion Speed',
    spec_amplitude: 'Stall Amplitude',
    spec_stall_force: 'Stall Resistance',
    spec_gears: 'Gear Shifting System',
    spec_wheelset: 'Wheelset Construction',
    spec_plates: 'Dumbbell Plate Material',
    spec_adjustment: 'Selector Mechanism',
    spec_thickness: 'Mat Thickness',
    spec_seasons: 'Seasons Rating',
    spec_poles: 'Tent Pole Material',
    spec_walls: 'Double Walls Design',
    spec_display_details: 'Cycle Computer Display',
    spec_sensors: 'Tracking Sensors',
    spec_battery_life: 'GPS Battery Life',
    spec_chambers: 'Inflation Chambers',
    spec_modes: 'Recovery Modes',
    spec_lens: 'Goggles Lens Type',
    spec_gasket: 'Eye Gasket Gasket',
    spec_strap: 'Goggles Strap Design',
    spec_volume: 'Backpack Volume',
    spec_closure: 'Dry Bag Closure',
    spec_active_retinol: 'Retinol Percentage',
    spec_skin_type: 'Skin Suitability',
    spec_packaging: 'Dropper Bottle Design',
    spec_pulsations: 'Pulse Speed',
    spec_intensity_levels: 'Brush Speeds',
    spec_ph_level: 'pH Balance Rating',
    spec_scent: 'Fragrance Profile',
    spec_sulfate_free: 'Sulfate Free Details',
    spec_kit_includes: 'Kit Contents List',
    spec_certificates: 'Ethics Certificates',
    spec_notes: 'Fragrance Notes',
    spec_longevity: 'Fragrance Longevity',
    spec_active_ingredient: 'Active Component',
    spec_hair_type: 'Hair Suitability',
    spec_sunscreen_type: 'Sunscreen Protection',
    spec_spf_rating: 'SPF Factor PA',
    spec_zinc_oxide: 'Zinc Oxide %',
    spec_vitamin_c: 'Vitamin C %',
    spec_ferulic_acid: 'Ferulic Acid %',
    spec_frequency: 'Vibrating Brush Speed',
    spec_brushing_sensor: 'Smart Pressure Sensor',
    spec_active_botanicals: 'Active Herbs List',
    spec_form: 'Supplement Format',
    spec_shades: 'Lipstick Nude Shades',
    spec_wear_time: 'Smudge-proof Wear',
    spec_cruelty_free: 'Cruelty Free Details',
    spec_key_oils: 'Key Natural Oils',
    spec_absorption: 'Rapid Absorption',

    // Homepage & Extras
    new_collection_2026: 'New Collection 2026',
    hero_title_premium: 'Premium Products',
    hero_title_curated: 'Curated For You',
    hero_sub: '25+ products across 5 categories. Electronics, fashion, home goods, sports equipment, and beauty — all in one place.',
    shop_now: 'Shop Now',
    hero_stat_products_label: 'Products',
    hero_stat_rating_label: 'Avg Rating',
    hero_stat_shipping_label: 'Free Shipping',
    featured_products: 'Featured Products',
    featured_sub: 'Deals, new arrivals and staff picks',
    view_all: 'View all',
    trust_shipping_title: 'Free Shipping',
    trust_shipping_desc: 'Orders over $100',
    trust_returns_title: '30-Day Returns',
    trust_returns_desc: 'No questions asked',
    trust_payment_title: 'Secure Payment',
    trust_payment_desc: '256-bit SSL encryption',
    trust_quality_title: 'Quality Guarantee',
    trust_quality_desc: 'Handpicked products',
    promo_label: 'Limited Time Offer',
    promo_title: 'Free Shipping on All Orders Over $100',
    promo_desc: 'Use code at checkout for an extra 10% off your first order',
    new_arrivals: 'New Arrivals',
    new_arrivals_sub: 'The latest additions to our collection',
    see_all: 'See all',
    best_sellers: 'Best Sellers',
    best_sellers_sub: 'Most popular products this month',
    footer_brand_desc: 'Premium products curated for those who demand excellence. Quality you can trust, delivered to your door.',
    footer_support: 'Support',
    footer_help_center: 'Help Center',
    footer_shipping_returns: 'Shipping & Returns',
    footer_track_order: 'Track Order',
    footer_contact_us: 'Contact Us',
    footer_company: 'Company',
    footer_about: 'About',
    footer_careers: 'Careers',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms of Service',
    footer_rights: 'All rights reserved.',
    footer_ssl: 'SSL Secured',
    footer_returns: 'Free Returns',
    footer_shipping: 'Worldwide Shipping',
  },
  uk: {
    // Navbar & Common
    home: 'Головна',
    shop: 'Магазин',
    deals: 'Акції',
    wishlist: 'Обране',
    compare: 'Порівняння',
    cart: 'Кошик',
    profile: 'Профіль',
    my_profile: 'Мій Профіль',
    logout: 'Вийти',
    search_placeholder: 'Шукати товари, бренди...',
    free_shipping_hint: 'Додайте ще ${price} для безкоштовної доставки',
    
    // Auth Gate
    welcome_back: 'Раді бачити знову',
    create_account: 'Створити акаунт',
    auth_required: 'Потрібна реєстрація для доступу до Zenith Store',
    full_name: 'Повне ім\'я',
    email_address: 'Електронна пошта',
    password: 'Пароль',
    sign_in: 'Увійти',
    register: 'Зареєструватися',
    already_have_acc: 'Вже є акаунт?',
    dont_have_acc: 'Ще немає акаунта?',
    register_now: 'Зареєструватися',
    sign_in_now: 'Увійти',
    processing: 'Завантаження...',

    // Wishlist Page
    my_wishlist: 'Моє Обране',
    clear_wishlist: 'Очистити Обране',
    items_saved: 'товарів збережено',
    wishlist_empty: 'Ваш список обраного порожній',
    wishlist_empty_sub: 'Зберігайте товари, які вам сподобалися, щоб легко знайти їх пізніше.',
    explore_shop: 'Перейти до магазину',

    // Compare Page
    compare_products: 'Порівняння товарів',
    clear_all: 'Очистити все',
    items_selected: 'товарів обрано',
    no_compare: 'Немає товарів для порівняння',
    no_compare_sub: 'Додайте до 4 товарів з каталогу для порівняння пліч-о-пліч.',
    features: 'Характеристики',
    price: 'Ціна',
    category: 'Категорія',
    rating: 'Рейтинг',
    status: 'Статус',
    description: 'Опис',
    in_stock: 'В наявності',
    out_of_stock: 'Немає в наявності',
    add_to_cart: 'У кошик',
    added_to_cart: 'Додано',
    remove: 'Видалити',

    // Cart Page
    your_cart: 'Ваш кошик',
    items_in_cart: 'товарів у кошику',
    cart_empty: 'Ваш кошик порожній',
    cart_empty_sub: 'Здається, ви ще нічого не додали до кошика.',
    continue_shopping: 'Продовжити покупки',
    order_summary: 'Підсумок замовлення',
    subtotal: 'Вартість товарів',
    shipping: 'Доставка',
    free: 'Безкоштовно',
    tax: 'Орієнтовний податок',
    total: 'Всього до сплати',
    proceed_checkout: 'Оформити замовлення',

    // Catalog & Filters
    filters: 'Фільтри',
    clear_filters: 'Очистити фільтри',
    search: 'Пошук',
    price_range: 'Діапазон цін',
    min_rating: 'Мін. рейтинг',
    in_stock_only: 'Тільки в наявності',
    sort_by: 'Сортування',
    showing: 'Показано',
    of: 'з',
    products: 'товарів',
    no_products: 'Товарів не знайдено',
    no_products_sub: 'Спробуйте змінити параметри фільтрів',
    
    // Sort Options
    sort_featured: 'Рекомендовані',
    sort_price_asc: 'Ціна: від низької до високої',
    sort_price_desc: 'Ціна: від високої до низької',
    sort_rating: 'Найкращий рейтинг',
    sort_newest: 'Спочатку нові',

    // Category translations
    category_all: 'Всі',
    category_electronics: 'Електроніка',
    category_clothing: 'Одяг',
    category_home: 'Дім',
    category_sports: 'Спорт',
    category_beauty: 'Краса',

    // Subcategory translations
    subcategory_laptops: 'Ноутбуки',
    subcategory_audio: 'Аудіо',
    subcategory_wearables: 'Носимі пристрої',
    subcategory_monitors: 'Монітори',
    subcategory_cameras: 'Камери',
    subcategory_accessories: 'Аксесуари',
    subcategory_vr: 'Віртуальна реальність',
    subcategory_outerwear: 'Верхній одяг',
    subcategory_footwear: 'Взуття',
    subcategory_tops: 'Верхній одяг/Топи',
    subcategory_activewear: 'Спортивний одяг',
    subcategory_lighting: 'Освітлення',
    subcategory_appliances: 'Побутова техніка',
    subcategory_kitchen: 'Кухня',
    subcategory_bedding: 'Постіль',
    subcategory_furniture: 'Меблі',
    subcategory_security: 'Безпека',
    subcategory_decor: 'Декор',
    subcategory_fitness_equipment: 'Фітнес обладнання',
    subcategory_cycling: 'Велоспорт',
    subcategory_swimming: 'Плавання',
    subcategory_recovery: 'Відновлення',
    subcategory_yoga: 'Йога',
    subcategory_outdoor: 'Активний відпочинок',
    subcategory_skincare: 'Догляд за шкірою',
    subcategory_wellness: 'Здоров\'я',
    subcategory_fragrance: 'Парфуми',
    subcategory_haircare: 'Догляд за волоссям',
    subcategory_cosmetics: 'Косметика',

    // Spec key translations
    spec_cpu: 'Процесор',
    spec_ram: 'Оперативна пам\'ять',
    spec_storage: 'Накопичувач',
    spec_display: 'Дисплей',
    spec_driver: 'Динамік',
    spec_anc: 'Шумозаглушення',
    spec_battery: 'Акумулятор',
    spec_connectivity: 'Підключення',
    spec_case: 'Корпус',
    spec_health: 'Показники здоров\'я',
    spec_resolution: 'Роздільна здатність',
    spec_refresh_rate: 'Частота оновлення',
    spec_panel: 'Тип панелі',
    spec_hdr: 'Підтримка HDR',
    spec_video: 'Режим відео',
    spec_stabilization: 'Стабілізація',
    spec_waterproof: 'Водонепроникність',
    spec_screen: 'Екран',
    spec_channels: 'Звукові канали',
    spec_power: 'Загальна потужність',
    spec_subwoofer: 'Сабвуфер',
    spec_material: 'Матеріал',
    spec_weight: 'Вага',
    spec_breathability: 'Повітропроникність',
    spec_plate: 'Амортизаційна пластина',
    spec_midsole: 'Технологія підошви',
    spec_upper: 'Матеріал верху',
    spec_drop: 'Перепад висоти',
    spec_fit: 'Посадка',
    spec_origin: 'Країна виробництва',
    spec_stretch: 'Еластичність',
    spec_liner: 'Внутрішній підклад',
    spec_pockets: 'Кишені',
    spec_wattage: 'Потужність лампи',
    spec_color_temp: 'Колірна температура',
    spec_brightness: 'Яскравість',
    spec_integration: 'Розумний асистент',
    spec_coverage: 'Площа очищення',
    spec_filter: 'Система фільтрації',
    spec_cadr: 'Показник очищення CADR',
    spec_noise: 'Рівень шуму',
    spec_pressure: 'Тиск помпи',
    spec_grinder: 'Кавомолка',
    spec_water_tank: 'Об\'єм резервуара води',
    spec_bean_hopper: 'Контейнер для зерен',
    spec_weights: 'Варіанти ваги',
    spec_fill: 'Наповнювач',
    spec_cover: 'Чохол',
    spec_thread_count: 'Щільність ниток',
    spec_steel: 'Тип сталі',
    spec_hardness: 'Твердість леза',
    spec_pieces: 'Кількість предметів',
    spec_block: 'Підставка',
    spec_height_range: 'Діапазон висоти столу',
    spec_motors: 'Підйомні двигуни',
    spec_tabletop: 'Матеріал стільниці',
    spec_load_capacity: 'Вантажопідйомність',
    spec_adjustments: 'Регулювання',
    spec_backrest: 'Дизайн спинки',
    spec_base: 'Конструкція бази',
    spec_suction: 'Сила всмоктування',
    spec_navigation: 'Навігація',
    spec_runtime: 'Час роботи',
    spec_dustbin: 'Контейнер для пилу',
    spec_charging: 'Бездротова зарядка',
    spec_bulb: 'Світлодіодна лампа',
    spec_port: 'Порти живлення',
    spec_entry_methods: 'Способи відмикання',
    spec_lock_type: 'Тип замка',
    spec_diameter: 'Діаметр плафона',
    spec_cord_length: 'Довжина кабелю',
    spec_socket: 'Тип цоколя',
    spec_fabric: 'Матеріал оббивки',
    spec_legs: 'Матеріал ніжок',
    spec_seat_height: 'Висота сидіння',
    spec_capacity: 'Об\'єм',
    spec_infuser: 'Заварювальний фільтр',
    spec_stove_safe: 'Використання на плиті',
    spec_includes: 'Комплектація',
    spec_sizes: 'Розміри',
    spec_finishes: 'Покриття вази',
    spec_cable_system: 'Тросова система',
    spec_footprint: 'Займана площа',
    spec_travel: 'Хід підвіски',
    spec_drivetrain: 'Трансмісія',
    spec_wheel_size: 'Діаметр коліс',
    spec_buoyancy: 'Плавучість гідрокостюма',
    spec_seams: 'Шви',
    spec_percussions: 'Швидкість ударів',
    spec_amplitude: 'Амплітуда',
    spec_stall_force: 'Зусилля блокування',
    spec_gears: 'Перемикання передач',
    spec_wheelset: 'Вілсет',
    spec_plates: 'Матеріал дисків гантелей',
    spec_adjustment: 'Механізм вибору ваги',
    spec_thickness: 'Товщина килимка',
    spec_seasons: 'Сезонність',
    spec_poles: 'Матеріал дуг',
    spec_walls: 'Конструкція стінок',
    spec_display_details: 'Дисплей комп\'ютера',
    spec_sensors: 'Датчики',
    spec_battery_life: 'Час автономної роботи',
    spec_chambers: 'Повітряні камери',
    spec_modes: 'Режими відновлення',
    spec_lens: 'Лінзи окулярів',
    spec_gasket: 'Ущільнювач для очей',
    spec_strap: 'Ремінець окулярів',
    spec_volume: 'Об\'єм рюкзака',
    spec_closure: 'Тип закриття dry-bag',
    spec_active_retinol: 'Відсоток ретинолу',
    spec_skin_type: 'Сумісність зі шкірою',
    spec_packaging: 'Дизайн флакона',
    spec_pulsations: 'Частота пульсацій',
    spec_intensity_levels: 'Режими швидкості',
    spec_ph_level: 'Рівень pH',
    spec_scent: 'Аромат',
    spec_sulfate_free: 'Без сульфатів',
    spec_kit_includes: 'Склад комплекту',
    spec_certificates: 'Сертифікати етичності',
    spec_notes: 'Ноти аромату',
    spec_longevity: 'Стійкість аромату',
    spec_active_ingredient: 'Активний компонент',
    spec_hair_type: 'Сумісність з волоссям',
    spec_sunscreen_type: 'Тип захисту SPF',
    spec_spf_rating: 'Коефіцієнт SPF PA',
    spec_zinc_oxide: 'Оксид цинку %',
    spec_vitamin_c: 'Вітамін C %',
    spec_ferulic_acid: 'Ферулова кислота %',
    spec_frequency: 'Частота вібрацій',
    spec_brushing_sensor: 'Датчик тиску при чищенні',
    spec_active_botanicals: 'Активні екстракти',
    spec_form: 'Форма добавки',
    spec_shades: 'Відтінки помади',
    spec_wear_time: 'Стійкість макіяжу',
    spec_cruelty_free: 'Не тестується на тваринах',
    spec_key_oils: 'Натуральні олії',
    spec_absorption: 'Швидкість всмоктування',

    // Homepage & Extras
    new_collection_2026: 'Нова колекція 2026',
    hero_title_premium: 'Преміум товари',
    hero_title_curated: 'Підібрано для вас',
    hero_sub: 'Більше 25 товарів у 5 категоріях. Електроніка, одяг, товари для дому, спорт та краса — все в одному місці.',
    shop_now: 'Купити зараз',
    hero_stat_products_label: 'Товарів',
    hero_stat_rating_label: 'Сер. рейтинг',
    hero_stat_shipping_label: 'Безкошт. доставка',
    featured_products: 'Рекомендовані товари',
    featured_sub: 'Акції, новинки та вибір редакції',
    view_all: 'Дивитись всі',
    trust_shipping_title: 'Безкоштовна доставка',
    trust_shipping_desc: 'Замовлення від $100',
    trust_returns_title: 'Повернення 30 днів',
    trust_returns_desc: 'Без зайвих запитань',
    trust_payment_title: 'Безпечна оплата',
    trust_payment_desc: '256-бітна SSL-безпека',
    trust_quality_title: 'Гарантія якості',
    trust_quality_desc: 'Ретельно відібрані товари',
    promo_label: 'Обмежена за часом пропозиція',
    promo_title: 'Безкоштовна доставка на всі замовлення від $100',
    promo_desc: 'Використовуйте промокод для знижки 10% на перше замовлення',
    new_arrivals: 'Нові надходження',
    new_arrivals_sub: 'Останні додані новинки нашої колекції',
    see_all: 'Дивитись все',
    best_sellers: 'Хіти продажу',
    best_sellers_sub: 'Найпопулярніші товари цього місяця',
    footer_brand_desc: 'Преміальні товари, підібрані для тих, хто вимагає досконалості. Якість, якій можна довіряти, з доставкою до дверей.',
    footer_support: 'Підтримка',
    footer_help_center: 'Довідковий центр',
    footer_shipping_returns: 'Доставка та повернення',
    footer_track_order: 'Відстежити замовлення',
    footer_contact_us: 'Зв\'язатися з нами',
    footer_company: 'Компанія',
    footer_about: 'Про нас',
    footer_careers: 'Вакансії',
    footer_privacy: 'Політика конфіденційності',
    footer_terms: 'Умови надання послуг',
    footer_rights: 'Усі права захищено.',
    footer_ssl: 'SSL Захищено',
    footer_returns: 'Безкоштовне повернення',
    footer_shipping: 'Доставка по всьому світу',
  },
  es: {
    // Navbar & Common
    home: 'Inicio',
    shop: 'Tienda',
    deals: 'Ofertas',
    wishlist: 'Favoritos',
    compare: 'Comparar',
    cart: 'Carrito',
    search_placeholder: 'Buscar productos, marcas...',
    logout: 'Cerrar sesión',
    free_shipping_hint: 'Agrega ${price} más para envío gratis',
    
    // Auth Gate
    welcome_back: 'Bienvenido de nuevo',
    create_account: 'Crear una cuenta',
    auth_required: 'Se requiere registro para acceder a Zenith Store',
    full_name: 'Nombre completo',
    email_address: 'Correo electrónico',
    password: 'Contraseña',
    sign_in: 'Iniciar sesión',
    register: 'Registrarse',
    already_have_acc: '¿Ya tienes una cuenta?',
    dont_have_acc: '¿Aún no tienes cuenta?',
    register_now: 'Regístrate ahora',
    sign_in_now: 'Iniciar sesión',
    processing: 'Procesando...',

    // Wishlist Page
    my_wishlist: 'Mis Favoritos',
    clear_wishlist: 'Limpiar Favoritos',
    items_saved: 'artículos guardados',
    wishlist_empty: 'Tu lista de favoritos está vacía',
    wishlist_empty_sub: 'Guarda los artículos que te encantan aquí para encontrarlos fácilmente más tarde.',
    explore_shop: 'Explorar tienda',

    // Compare Page
    compare_products: 'Comparar Productos',
    clear_all: 'Limpiar todo',
    items_selected: 'artículos seleccionados',
    no_compare: 'No hay productos para comparar',
    no_compare_sub: 'Agrega hasta 4 artículos de la tienda para compararlos lado a lado.',
    features: 'Características',
    price: 'Precio',
    category: 'Categoría',
    rating: 'Calificación',
    status: 'Estado',
    description: 'Descripción',
    in_stock: 'En stock',
    out_of_stock: 'Agotado',
    add_to_cart: 'Añadir al carrito',
    added_to_cart: 'Añadido',
    remove: 'Eliminar',

    // Cart Page
    your_cart: 'Tu Carrito de Compras',
    items_in_cart: 'artículos en el carrito',
    cart_empty: 'Tu carrito está vacío',
    cart_empty_sub: 'Parece que aún no has añadido nada a tu carrito.',
    continue_shopping: 'Continuar comprando',
    order_summary: 'Resumen del pedido',
    subtotal: 'Subtotal',
    shipping: 'Envío',
    free: 'Gratis',
    tax: 'Impuesto estimado',
    total: 'Total',
    proceed_checkout: 'Proceder al pago',

    // Catalog & Filters
    filters: 'Filtros',
    clear_filters: 'Limpiar filtros',
    search: 'Buscar',
    price_range: 'Rango de precios',
    min_rating: 'Calificación mínima',
    in_stock_only: 'Solo en stock',
    sort_by: 'Ordenar por',
    showing: 'Mostrando',
    of: 'de',
    products: 'productos',
    no_products: 'No se encontraron productos',
    no_products_sub: 'Intenta ajustar tus filtros',
    
    // Sort Options
    sort_featured: 'Destacados',
    sort_price_asc: 'Precio: bajo a alto',
    sort_price_desc: 'Precio: alto a bajo',
    sort_rating: 'Mejor calificados',
    sort_newest: 'Más nuevos primero',

    // Category translations
    category_all: 'Todo',
    category_electronics: 'Electrónica',
    category_clothing: 'Ropa',
    category_home: 'Hogar',
    category_sports: 'Deportes',
    category_beauty: 'Belleza',

    // Subcategory translations
    subcategory_laptops: 'Portátiles',
    subcategory_audio: 'Audio',
    subcategory_wearables: 'Dispositivos portátiles',
    subcategory_monitors: 'Monitores',
    subcategory_cameras: 'Cámaras',
    subcategory_accessories: 'Accesorios',
    subcategory_vr: 'VR',
    subcategory_outerwear: 'Ropa de abrigo',
    subcategory_footwear: 'Calzado',
    subcategory_tops: 'Camisetas y Tops',
    subcategory_activewear: 'Ropa deportiva',
    subcategory_lighting: 'Iluminación',
    subcategory_appliances: 'Electrodomésticos',
    subcategory_kitchen: 'Cocina',
    subcategory_bedding: 'Ropa de cama',
    subcategory_furniture: 'Muebles',
    subcategory_security: 'Seguridad',
    subcategory_decor: 'Decoración',
    subcategory_fitness_equipment: 'Equipos de fitness',
    subcategory_cycling: 'Ciclismo',
    subcategory_swimming: 'Natación',
    subcategory_recovery: 'Recuperación',
    subcategory_yoga: 'Yoga',
    subcategory_outdoor: 'Al aire libre',
    subcategory_skincare: 'Cuidado de la piel',
    subcategory_wellness: 'Bienestar',
    subcategory_fragrance: 'Fragancias',
    subcategory_haircare: 'Cuidado del cabello',
    subcategory_cosmetics: 'Cosméticos',

    // Spec key translations
    spec_cpu: 'CPU',
    spec_ram: 'RAM',
    spec_storage: 'Almacenamiento',
    spec_display: 'Pantalla',
    spec_driver: 'Controlador de audio',
    spec_anc: 'ANC',
    spec_battery: 'Batería',
    spec_connectivity: 'Conectividad',
    spec_case: 'Caja del reloj',
    spec_health: 'Métricas de salud',
    spec_resolution: 'Resolución',
    spec_refresh_rate: 'Frecuencia de actualización',
    spec_panel: 'Tipo de panel',
    spec_hdr: 'Soporte HDR',
    spec_video: 'Resolución de video',
    spec_stabilization: 'Estabilización',
    spec_waterproof: 'Profundidad de agua',
    spec_screen: 'Tamaño de pantalla',
    spec_channels: 'Canales de sonido',
    spec_power: 'Potencia total',
    spec_subwoofer: 'Tamaño de subwoofer',
    spec_material: 'Material',
    spec_weight: 'Peso',
    spec_breathability: 'Transpirabilidad',
    spec_plate: 'Placa de propulsión',
    spec_midsole: 'Tecnología de entresuela',
    spec_upper: 'Material superior',
    spec_drop: 'Caída del talón',
    spec_fit: 'Ajuste',
    spec_origin: 'País de origen',
    spec_stretch: 'Elasticidad del material',
    spec_liner: 'Forro integrado',
    spec_pockets: 'Diseño de bolsillos',
    spec_wattage: 'Potencia de bombilla',
    spec_color_temp: 'Temperatura de color',
    spec_brightness: 'Brillo máximo',
    spec_integration: 'Asistente inteligente',
    spec_coverage: 'Área de cobertura',
    spec_filter: 'Filtros de aire',
    spec_cadr: 'Clasificación CADR',
    spec_noise: 'Ruido de operación',
    spec_pressure: 'Presión de bomba',
    spec_grinder: 'Molinillo de café',
    spec_water_tank: 'Tanque de agua',
    spec_bean_hopper: 'Contenedor de granos',
    spec_weights: 'Pesos disponibles',
    spec_fill: 'Relleno interno',
    spec_cover: 'Funda extraíble',
    spec_thread_count: 'Hilos por pulgada',
    spec_steel: 'Tipo de acero',
    spec_hardness: 'Dureza de hoja',
    spec_pieces: 'Piezas del juego',
    spec_block: 'Bloque de soporte',
    spec_height_range: 'Rango de altura de escritorio',
    spec_motors: 'Motores de elevación',
    spec_tabletop: 'Material de tablero',
    spec_load_capacity: 'Capacidad de carga',
    spec_adjustments: 'Ajustes disponibles',
    spec_backrest: 'Diseño de respaldo',
    spec_base: 'Construcción de base',
    spec_suction: 'Fuerza de succión',
    spec_navigation: 'Sistema de navegación',
    spec_runtime: 'Tiempo de ejecución',
    spec_dustbin: 'Capacidad de depósito',
    spec_charging: 'Potencia de carga Qi',
    spec_bulb: 'Detalles de bombilla LED',
    spec_port: 'Puertos de salida',
    spec_entry_methods: 'Métodos de desbloqueo',
    spec_lock_type: 'Tipo de cerradura',
    spec_diameter: 'Diámetro de pantalla',
    spec_cord_length: 'Longitud del cable',
    spec_socket: 'Tipo de casquillo',
    spec_fabric: 'Materiales de tela',
    spec_legs: 'Materiales de patas',
    spec_seat_height: 'Nivel de altura del asiento',
    spec_capacity: 'Volumen total',
    spec_infuser: 'Diseño de filtro',
    spec_stove_safe: 'Apto para estufas',
    spec_includes: 'Artículos incluidos',
    spec_sizes: 'Tallas disponibles',
    spec_finishes: 'Acabados de jarrón',
    spec_cable_system: 'Sistema de poleas',
    spec_footprint: 'Espacio de suelo',
    spec_travel: 'Recorrido de suspensión',
    spec_drivetrain: 'Transmisión de marchas',
    spec_wheel_size: 'Diámetro de ruedas',
    spec_buoyancy: 'Flotabilidad de neopreno',
    spec_seams: 'Costuras de traje',
    spec_percussions: 'Velocidad de percusión',
    spec_amplitude: 'Amplitud de parada',
    spec_stall_force: 'Resistencia al bloqueo',
    spec_gears: 'Sistema de cambios',
    spec_wheelset: 'Juego de ruedas',
    spec_plates: 'Material de discos',
    spec_adjustment: 'Mecanismo selector',
    spec_thickness: 'Grosor de esterilla',
    spec_seasons: 'Clasificación de estaciones',
    spec_poles: 'Material de varillas',
    spec_walls: 'Diseño de paredes',
    spec_display_details: 'Pantalla de ciclocomputador',
    spec_sensors: 'Sensores de seguimiento',
    spec_battery_life: 'Autonomía de GPS',
    spec_chambers: 'Cámaras de inflado',
    spec_modes: 'Modos de recuperación',
    spec_lens: 'Tipo de lentes',
    spec_gasket: 'Junta para los ojos',
    spec_strap: 'Diseño de correa',
    spec_volume: 'Volumen de mochila',
    spec_closure: 'Cierre de bolsa seca',
    spec_active_retinol: 'Porcentaje de retinol',
    spec_skin_type: 'Idoneidad de piel',
    spec_packaging: 'Diseño de gotero',
    spec_pulsations: 'Velocidad de pulsaciones',
    spec_intensity_levels: 'Ajustes del cepillo',
    spec_ph_level: 'Clasificación de pH',
    spec_scent: 'Perfil de fragancia',
    spec_sulfate_free: 'Detalles sin sulfatos',
    spec_kit_includes: 'Contenido del kit',
    spec_certificates: 'Certificados éticos',
    spec_notes: 'Notas de fragancia',
    spec_longevity: 'Duración de fragancia',
    spec_active_ingredient: 'Componente activo',
    spec_hair_type: 'Idoneidad de cabello',
    spec_sunscreen_type: 'Tipo de protección solar',
    spec_spf_rating: 'Factor de protección solar PA',
    spec_zinc_oxide: '% de óxido de zinc',
    spec_vitamin_c: '% de vitamina C',
    spec_ferulic_acid: '% de ácido ferúlico',
    spec_frequency: 'Velocidad de cepillado',
    spec_brushing_sensor: 'Sensor de presión inteligente',
    spec_active_botanicals: 'Hierbas activas',
    spec_form: 'Formato de suplemento',
    spec_shades: 'Tonos de lápiz labial',
    spec_wear_time: 'Duración del labial',
    spec_cruelty_free: 'Detalles sin crueldad',
    spec_key_oils: 'Aceites naturales clave',
    spec_absorption: 'Absorción rápida',

    // Homepage & Extras
    new_collection_2026: 'Nueva colección 2026',
    hero_title_premium: 'Productos Premium',
    hero_title_curated: 'Seleccionados para ti',
    hero_sub: 'Más de 25 productos en 5 categorías. Electrónica, moda, hogar, deportes y belleza, todo en un solo lugar.',
    shop_now: 'Comprar ahora',
    hero_stat_products_label: 'Productos',
    hero_stat_rating_label: 'Calificación prom.',
    hero_stat_shipping_label: 'Envío gratis',
    featured_products: 'Productos destacados',
    featured_sub: 'Ofertas, novedades y selección del editor',
    view_all: 'Ver todo',
    trust_shipping_title: 'Envío gratis',
    trust_shipping_desc: 'Pedidos superiores a $100',
    trust_returns_title: 'Devoluciones de 30 días',
    trust_returns_desc: 'Sin preguntas',
    trust_payment_title: 'Pago seguro',
    trust_payment_desc: 'Cifrado SSL de 256 bits',
    trust_quality_title: 'Garantía de calidad',
    trust_quality_desc: 'Productos seleccionados',
    promo_label: 'Oferta por tiempo limitado',
    promo_title: 'Envío gratis en todos los pedidos superiores a $100',
    promo_desc: 'Usa el código al pagar para obtener un 10% de descuento adicional',
    new_arrivals: 'Novedades',
    new_arrivals_sub: 'Las últimas incorporaciones a nuestra colección',
    see_all: 'Ver todo',
    best_sellers: 'Los más vendidos',
    best_sellers_sub: 'Los productos más populares este mes',
    footer_brand_desc: 'Productos premium seleccionados para quienes exigen excelencia. Calidad en la que puede confiar, entregada en su puerta.',
    footer_support: 'Soporte',
    footer_help_center: 'Centro de ayuda',
    footer_shipping_returns: 'Envíos y devoluciones',
    footer_track_order: 'Seguimiento de pedido',
    footer_contact_us: 'Contáctenos',
    footer_company: 'Compañía',
    footer_about: 'Acerca de',
    footer_careers: 'Empleo',
    footer_privacy: 'Política de privacidad',
    footer_terms: 'Términos de servicio',
    footer_rights: 'Todos los derechos reservados.',
    footer_ssl: 'Seguridad SSL',
    footer_returns: 'Devoluciones gratis',
    footer_shipping: 'Envío mundial',
  },
  de: {
    // Navbar & Common
    home: 'Startseite',
    shop: 'Shop',
    deals: 'Angebote',
    wishlist: 'Wunschzettel',
    compare: 'Vergleichen',
    cart: 'Warenkorb',
    search_placeholder: 'Produkte, Marken suchen...',
    logout: 'Abmelden',
    free_shipping_hint: 'Noch ${price} hinzufügen für kostenlosen Versand',
    
    // Auth Gate
    welcome_back: 'Willkommen zurück',
    create_account: 'Konto erstellen',
    auth_required: 'Eine Registrierung ist erforderlich, um den Zenith Store zu besuchen',
    full_name: 'Vollständiger Name',
    email_address: 'E-Mail-Adresse',
    password: 'Passwort',
    sign_in: 'Einloggen',
    register: 'Registrieren',
    already_have_acc: 'Bereits ein Konto?',
    dont_have_acc: 'Noch kein Konto?',
    register_now: 'Jetzt registrieren',
    sign_in_now: 'Einloggen',
    processing: 'Wird verarbeitet...',

    // Wishlist Page
    my_wishlist: 'Mein Wunschzettel',
    clear_wishlist: 'Wunschzettel leeren',
    items_saved: 'Artikel gespeichert',
    wishlist_empty: 'Ihr Wunschzettel ist leer',
    wishlist_empty_sub: 'Speichern Sie Ihre Lieblingsartikel hier, um sie später wiederzufinden.',
    explore_shop: 'Shop erkunden',

    // Compare Page
    compare_products: 'Produkte vergleichen',
    clear_all: 'Alles löschen',
    items_selected: 'Artikel ausgewählt',
    no_compare: 'Keine Produkte zum Vergleichen',
    no_compare_sub: 'Fügen Sie bis zu 4 Artikel aus dem Shop hinzu, um sie direkt zu vergleichen.',
    features: 'Eigenschaften',
    price: 'Preis',
    category: 'Kategorie',
    rating: 'Bewertung',
    status: 'Status',
    description: 'Beschreibung',
    in_stock: 'Auf Lager',
    out_of_stock: 'Nicht auf Lager',
    add_to_cart: 'In den Warenkorb',
    added_to_cart: 'Hinzugefügt',
    remove: 'Entfernen',

    // Cart Page
    your_cart: 'Ihr Warenkorb',
    items_in_cart: 'Artikel im Warenkorb',
    cart_empty: 'Ihr Warenkorb ist leer',
    cart_empty_sub: 'Es sieht so aus, als hätten Sie noch keine Artikel hinzugefügt.',
    continue_shopping: 'Weiter einkaufen',
    order_summary: 'Bestellübersicht',
    subtotal: 'Zwischensumme',
    shipping: 'Versand',
    free: 'Kostenlos',
    tax: 'Geschätzte Steuer',
    total: 'Gesamtsumme',
    proceed_checkout: 'Zur Kasse gehen',

    // Catalog & Filters
    filters: 'Filter',
    clear_filters: 'Filter löschen',
    search: 'Suche',
    price_range: 'Preisspanne',
    min_rating: 'Mindestbewertung',
    in_stock_only: 'Nur auf Lager',
    sort_by: 'Sortieren nach',
    showing: 'Zeige',
    of: 'von',
    products: 'Produkten',
    no_products: 'Keine Produkte gefunden',
    no_products_sub: 'Versuchen Sie, Ihre Filter anzupassen',
    
    // Sort Options
    sort_featured: 'Vorgestellt',
    sort_price_asc: 'Preis: Niedrig bis Hoch',
    sort_price_desc: 'Preis: Hoch bis Niedrig',
    sort_rating: 'Beste Bewertung',
    sort_newest: 'Neueste zuerst',

    // Category translations
    category_all: 'Alle',
    category_electronics: 'Elektronik',
    category_clothing: 'Kleidung',
    category_home: 'Home & Wohnen',
    category_sports: 'Sport & Outdoor',
    category_beauty: 'Schönheit & Pflege',

    // Subcategory translations
    subcategory_laptops: 'Laptops',
    subcategory_audio: 'Audio',
    subcategory_wearables: 'Wearables',
    subcategory_monitors: 'Monitoren',
    subcategory_cameras: 'Kameras',
    subcategory_accessories: 'Zubehör',
    subcategory_vr: 'Virtual Reality',
    subcategory_outerwear: 'Oberbekleidung',
    subcategory_footwear: 'Schuhe',
    subcategory_tops: 'Oberteile',
    subcategory_activewear: 'Sportbekleidung',
    subcategory_lighting: 'Beleuchtung',
    subcategory_appliances: 'Haushaltsgeräte',
    subcategory_kitchen: 'Küche',
    subcategory_bedding: 'Bettwaren',
    subcategory_furniture: 'Möbel',
    subcategory_security: 'Sicherheit',
    subcategory_decor: 'Dekoration',
    subcategory_fitness_equipment: 'Fitnessgeräte',
    subcategory_cycling: 'Radsport',
    subcategory_swimming: 'Schwimmen',
    subcategory_recovery: 'Regeneration',
    subcategory_yoga: 'Yoga',
    subcategory_outdoor: 'Outdoor',
    subcategory_skincare: 'Hautpflege',
    subcategory_wellness: 'Wellness',
    subcategory_fragrance: 'Parfüm',
    subcategory_haircare: 'Haarpflege',
    subcategory_cosmetics: 'Kosmetik',

    // Spec key translations
    spec_cpu: 'CPU-Prozessor',
    spec_ram: 'Arbeitsspeicher',
    spec_storage: 'Speicherkapazität',
    spec_display: 'Displaytyp',
    spec_driver: 'Lautsprechertreiber',
    spec_anc: 'Geräuschunterdrückung',
    spec_battery: 'Akkukapazität',
    spec_connectivity: 'Konnektivität',
    spec_case: 'Uhrengehäuse',
    spec_health: 'Gesundheitswerte',
    spec_resolution: 'Bildschirmauflösung',
    spec_refresh_rate: 'Bildwiederholfrequenz',
    spec_panel: 'Paneltyp',
    spec_hdr: 'HDR-Unterstützung',
    spec_video: 'Videoauflösung',
    spec_stabilization: 'Videostabilisierung',
    spec_waterproof: 'Wasserdichtigkeit',
    spec_screen: 'Bildschirmdiagonale',
    spec_channels: 'Tonkanäle',
    spec_power: 'Gesamtleistung',
    spec_subwoofer: 'Subwoofer-Größe',
    spec_material: 'Material',
    spec_weight: 'Gewicht',
    spec_breathability: 'Atmungsaktivität',
    spec_plate: 'Antriebsplatte',
    spec_midsole: 'Zwischensohlentechnik',
    spec_upper: 'Obermaterial',
    spec_drop: 'Fersensprengung',
    spec_fit: 'Passform',
    spec_origin: 'Hergestellt in',
    spec_stretch: 'Materialdehnung',
    spec_liner: 'Innenfutter',
    spec_pockets: 'Taschendesign',
    spec_wattage: 'Glühbirnenleistung',
    spec_color_temp: 'Farbtemperatur',
    spec_brightness: 'Max. Helligkeit',
    spec_integration: 'Sprachassistent',
    spec_coverage: 'Raumabdeckung',
    spec_filter: 'Filterstufen',
    spec_cadr: 'CADR-Luftreinigungsrate',
    spec_noise: 'Betriebsgeräusch',
    spec_pressure: 'Pumpendruck',
    spec_grinder: 'Kaffeemühle',
    spec_water_tank: 'Wassertankgröße',
    spec_bean_hopper: 'Bohnenbehältergröße',
    spec_weights: 'Verfügbare Gewichte',
    spec_fill: 'Füllung',
    spec_cover: 'Abnehmbarer Bezug',
    spec_thread_count: 'Fadendichte',
    spec_steel: 'Stahlsorte',
    spec_hardness: 'Klingenhärte',
    spec_pieces: 'Set-Teile',
    spec_block: 'Messerblock',
    spec_height_range: 'Höhenbereich',
    spec_motors: 'Hubmotoren',
    spec_tabletop: 'Tischplattenmaterial',
    spec_load_capacity: 'Tragfähigkeit',
    spec_adjustments: 'Einstellmöglichkeiten',
    spec_backrest: 'Rückenlehnendesign',
    spec_base: 'Fahrgestell',
    spec_suction: 'Saugleistung',
    spec_navigation: 'Navigationssystem',
    spec_runtime: 'Max. Akkulaufzeit',
    spec_dustbin: 'Staubbehältergröße',
    spec_charging: 'Qi-Ladeleistung',
    spec_bulb: 'LED-Leuchtmitteldetails',
    spec_port: 'Stromausgangsports',
    spec_entry_methods: 'Entsperrmethoden',
    spec_lock_type: 'Schlosstyp',
    spec_diameter: 'Schirmdurchmesser',
    spec_cord_length: 'Kabellänge',
    spec_socket: 'Lampensockel',
    spec_fabric: 'Polsterstoff',
    spec_legs: 'Beinmaterial',
    spec_seat_height: 'Sitzhöhe',
    spec_capacity: 'Volumen',
    spec_infuser: 'Siebfilterdesign',
    spec_stove_safe: 'Herdkompatibilität',
    spec_includes: 'Lieferumfang',
    spec_sizes: 'Verfügbare Größen',
    spec_finishes: 'Vasenoberflächen',
    spec_cable_system: 'Seilzuggewicht',
    spec_footprint: 'Stellfläche',
    spec_travel: 'Federweg',
    spec_drivetrain: 'Schaltgruppe',
    spec_wheel_size: 'Raddurchmesser',
    spec_buoyancy: 'Neopren-Auftrieb',
    spec_seams: 'Nahtkonstruktion',
    spec_percussions: 'Schlagzahl',
    spec_amplitude: 'Hubamplitude',
    spec_stall_force: 'Blockierkraft',
    spec_gears: 'Schaltung',
    spec_wheelset: 'Laufradsatz',
    spec_plates: 'Hantelscheibenmaterial',
    spec_adjustment: 'Wählmechanismus',
    spec_thickness: 'Mattenstärke',
    spec_seasons: 'Jahreszeiten-Eignung',
    spec_poles: 'Gestängematerial',
    spec_walls: 'Wandkonstruktion',
    spec_display_details: 'Fahrradcomputer-Display',
    spec_sensors: 'Sensoren',
    spec_battery_life: 'GPS-Akkulaufzeit',
    spec_chambers: 'Luftkammern',
    spec_modes: 'Erholungsmodi',
    spec_lens: 'Linsentyp',
    spec_gasket: 'Dichtungslippe',
    spec_strap: 'Brillenband-Design',
    spec_volume: 'Rucksackvolumen',
    spec_closure: 'Rollverschluss',
    spec_active_retinol: 'Retinol-Prozentsatz',
    spec_skin_type: 'Hauttyp-Eignung',
    spec_packaging: 'Pipettenflaschendesign',
    spec_pulsations: 'Pulsationsfrequenz',
    spec_intensity_levels: 'Bürstenstufen',
    spec_ph_level: 'pH-Wert',
    spec_scent: 'Duftnote',
    spec_sulfate_free: 'Sulfatfrei-Details',
    spec_kit_includes: 'Kit-Inhalt',
    spec_certificates: 'Ethik-Zertifikate',
    spec_notes: 'Duftnoten-Details',
    spec_longevity: 'Duft-Haltbarkeit',
    spec_active_ingredient: 'Wirkstoff',
    spec_hair_type: 'Haartyp-Eignung',
    spec_sunscreen_type: 'Sonnencreme-Typ',
    spec_spf_rating: 'Lichtschutzfaktor PA',
    spec_zinc_oxide: 'Zinkoxid-Anteil %',
    spec_vitamin_c: 'Vitamin C-Anteil %',
    spec_ferulic_acid: 'Ferulasäure-Anteil %',
    spec_frequency: 'Schwingungszahl',
    spec_brushing_sensor: 'Andrucksensor',
    spec_active_botanicals: 'Aktive Kräuter',
    spec_form: 'Darreichungsform',
    spec_shades: 'Lippenstiftnuancen',
    spec_wear_time: 'Kussfestigkeit',
    spec_cruelty_free: 'Tierversuchsfrei-Eignung',
    spec_key_oils: 'Ätherische Hauptöle',
    spec_absorption: 'Einziehzeit',

    // Homepage & Extras
    new_collection_2026: 'Neue Kollektion 2026',
    hero_title_premium: 'Premium-Produkte',
    hero_title_curated: 'Für Sie kuratiert',
    hero_sub: '25+ Produkte in 5 Kategorien. Elektronik, Mode, Haushaltswaren, Sportgeräte und Schönheit – alles an einem Ort.',
    shop_now: 'Jetzt shoppen',
    hero_stat_products_label: 'Produkte',
    hero_stat_rating_label: 'Durschn. Bewertung',
    hero_stat_shipping_label: 'Kostenloser Versand',
    featured_products: 'Beliebte Produkte',
    featured_sub: 'Angebote, Neuheiten und Empfehlungen',
    view_all: 'Alle anzeigen',
    trust_shipping_title: 'Kostenloser Versand',
    trust_shipping_desc: 'Bestellungen ab 100 $',
    trust_returns_title: '30 Tage Rückgaberecht',
    trust_returns_desc: 'Ohne Fragen',
    trust_payment_title: 'Sichere Zahlung',
    trust_payment_desc: '256-Bit-SSL-Verschlüsselung',
    trust_quality_title: 'Qualitätsgarantie',
    trust_quality_desc: 'Handverlesene Produkte',
    promo_label: 'Befristetes Angebot',
    promo_title: 'Kostenloser Versand für alle Bestellungen über 100 $',
    promo_desc: 'Code beim Checkout eingeben für zusätzliche 10 % Rabatt',
    new_arrivals: 'Neuheiten',
    new_arrivals_sub: 'Die neuesten Artikel in unserer Kollektion',
    see_all: 'Alle ansehen',
    best_sellers: 'Bestseller',
    best_sellers_sub: 'Die beliebtesten Produkte in diesem Monat',
    footer_brand_desc: 'Premium-Produkte für alle, die das Beste verlangen. Qualität, der Sie vertrauen können, direkt an Ihre Haustür geliefert.',
    footer_support: 'Support',
    footer_help_center: 'Hilfebereich',
    footer_shipping_returns: 'Versand & Rückgabe',
    footer_track_order: 'Bestellstatus',
    footer_contact_us: 'Kontakt',
    footer_company: 'Unternehmen',
    footer_about: 'Über uns',
    footer_careers: 'Karriere',
    footer_privacy: 'Datenschutzerklärung',
    footer_terms: 'Nutzungsbedingungen',
    footer_rights: 'Alle Rechte vorbehalten.',
    footer_ssl: 'SSL-gesichert',
    footer_returns: 'Kostenlose Rückgabe',
    footer_shipping: 'Weltweiter Versand',
  },
};

interface LanguageCtx {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, replacements?: Record<string, string>) => string;
  tProduct: (product: any) => any;
}

const Ctx = createContext<LanguageCtx | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    try {
      const saved = localStorage.getItem('zenith_lang') as Language;
      if (saved && (saved === 'en' || saved === 'uk' || saved === 'es' || saved === 'de')) {
        setLanguageState(saved);
      }
    } catch {}
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('zenith_lang', lang);
    } catch {}
  };

  const t = (key: string, replacements?: Record<string, string>): string => {
    const langDict = translations[language] || translations['en'];
    let text = langDict[key] || translations['en'][key];
    if (text === undefined) return key;
    
    if (replacements) {
      Object.entries(replacements).forEach(([k, v]) => {
        text = text.replace(`\${${k}}`, v);
      });
    }
    
    return text;
  };

  const tProduct = (product: any): any => {
    const formatKey = (str: string) => str.toLowerCase().replace(/[^a-z0-9]/g, '_');
    
    const getTranslationOrOriginal = (key: string, original: string) => {
      const langDict = translations[language] || translations['en'];
      const text = langDict[key] || translations['en'][key];
      return text !== undefined ? text : original;
    };
    
    const localProd = getProductTranslation(product.id, language, product.title, product.description);
    
    return {
      ...product,
      title: localProd.title,
      description: localProd.description,
      longDescription: getTranslationOrOriginal(`product_long_desc_${product.id}`, product.longDescription),
      category: getTranslationOrOriginal(`category_${formatKey(product.category)}`, product.category),
      subcategory: getTranslationOrOriginal(`subcategory_${formatKey(product.subcategory)}`, product.subcategory),
      specs: product.specs ? Object.entries(product.specs).reduce((acc, [k, v]) => {
        const transKey = `spec_${formatKey(k)}`;
        const transValKey = `spec_val_${formatKey(v as string)}`;
        acc[getTranslationOrOriginal(transKey, k)] = getTranslationOrOriginal(transValKey, v as string);
        return acc;
      }, {} as Record<string, string>) : undefined
    };
  };

  return (
    <Ctx.Provider value={{ language, setLanguage, t, tProduct }}>
      {children}
    </Ctx.Provider>
  );
}

export const useTranslation = () => {
  const ctx = useContext(Ctx);
  if (!ctx) throw new Error('useTranslation must be inside LanguageProvider');
  return ctx;
};
